"""ConfigService — effective config read/write, model catalog, capabilities, channels,
and async model probes.

Wraps ``durin.config``, ``durin.providers``, ``durin.channels``, and the
``durin.cli.doctor`` / ``durin.memory.cross_encoder`` probe helpers.

Async probes
------------
``model_test`` and ``cross_encoder_test`` are ``async def`` because they perform
genuine I/O (a live model round-trip and a potentially slow model-download+warmup).
Their service methods stay async; the shims ``await`` them. Inside the service,
``cross_encoder_test`` uses ``asyncio.to_thread`` to run the blocking ``probe_model``
call off the event loop — identical to the original handler.

``dict[str, Any]`` escape hatches
----------------------------------
- ``ConfigGetResult.config`` / ``.schema``: the effective config dict and its JSON
  schema are large, dynamic, provider-generated dicts. Typed as ``dict[str, Any]``
  escape hatches; SP3 can tighten sub-structure if needed.
- ``ModelsListResult.suggested`` / ``.models``: free-form string lists (``list[str]``
  typed properly).
- ``ModelCapabilitiesResult`` fields are typed scalars (no escape hatch needed).
- ``ChannelsListResult.channels``: list of channel-info dicts (``list[dict[str, Any]]``
  escape hatch — shape comes from the channel registry).

Extracted from ``durin/channels/websocket.py``
(``_handle_config_get`` / ``_handle_config_set`` / ``_handle_models_list`` /
``_handle_model_capabilities`` / ``_handle_channels_list`` / ``_handle_model_test`` /
``_handle_cross_encoder_test``) in SP1; the channel keeps wire-identical shims.
"""

from __future__ import annotations

from typing import Any

from pydantic import Field

from durin.service.principal import Principal, Scope
from durin.service.registry import route
from durin.service.types import (
    Command,
    Query,
    Result,
    ValidationFailedError,
)

# ---------------------------------------------------------------------------
# DTOs — config get
# ---------------------------------------------------------------------------


class ConfigGetQuery(Query):
    """No inputs — returns the full effective config + JSON schema."""


class ConfigGetResult(Result):
    """Full effective config (secrets masked) plus its JSON schema.

    Both fields are ``dict[str, Any]`` escape hatches: the config dict is
    dynamically assembled by pydantic and the schema is generated by
    ``Config.model_json_schema``.

    ``json_schema`` is aliased to ``"schema"`` on the wire because ``schema``
    is a reserved name on ``pydantic.BaseModel``.
    """

    config: dict[str, Any]
    json_schema: dict[str, Any] = Field(alias="schema")  # wire key: "schema"


# ---------------------------------------------------------------------------
# DTOs — config set
# ---------------------------------------------------------------------------


class ConfigSetCommand(Command):
    key: str
    value: str


class ConfigSetResult(Result):
    ok: bool
    config: dict[str, Any]  # escape hatch — full updated config, secrets masked


# ---------------------------------------------------------------------------
# DTOs — models list
# ---------------------------------------------------------------------------


class ModelsListQuery(Query):
    provider: str = ""
    capability: str = ""


class ModelsListResult(Result):
    suggested: list[str]
    models: list[str]


# ---------------------------------------------------------------------------
# DTOs — model capabilities
# ---------------------------------------------------------------------------


class ModelCapabilitiesQuery(Query):
    model: str
    provider: str | None = None


class ModelCapabilitiesResult(Result):
    model: str
    max_input_tokens: int | None
    supports_vision: bool
    supports_audio_input: bool
    supports_function_calling: bool
    supports_reasoning: bool


# ---------------------------------------------------------------------------
# DTOs — channels list
# ---------------------------------------------------------------------------


class ChannelsListQuery(Query):
    """No inputs — lists all discovered channels with their enabled state."""


class ChannelsListResult(Result):
    channels: list[dict[str, Any]]  # escape hatch — shape from channel registry


# ---------------------------------------------------------------------------
# DTOs — model test (async probe)
# ---------------------------------------------------------------------------


class ModelTestQuery(Query):
    model: str = ""
    provider: str = ""


class ModelTestResult(Result):
    status: str
    message: str
    fix: str


# ---------------------------------------------------------------------------
# DTOs — cross-encoder test (async probe)
# ---------------------------------------------------------------------------


class CrossEncoderTestQuery(Query):
    model: str


class CrossEncoderTestResult(Result):
    status: str
    message: str
    model_id: str
    duration_ms: float


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------

#: Credential field names, in priority order (first match wins).
_CRED_FIELDS: tuple[str, ...] = (
    "token", "bot_token", "app_token", "appId", "app_id",
    "api_key", "claw_token", "access_token",
)

#: Plan-variant → base provider for keyword lookup.
_PLAN_BASE: dict[str, str] = {
    "zai_coding_plan": "zhipu",
    "volcengine_coding_plan": "volcengine",
    "byteplus_coding_plan": "byteplus",
}


class ConfigService:
    """Read/write the effective config, list models/channels, probe model health."""

    @route(
        "GET",
        "/api/config",
        scope=Scope.CONFIG_READ.value,
        request_model=ConfigGetQuery,
        response_model=ConfigGetResult,
        summary="Return effective config (secrets masked) + JSON schema",
    )
    async def get(self, query: ConfigGetQuery, principal: Principal) -> ConfigGetResult:
        principal.require(Scope.CONFIG_READ)
        from durin.cli.config_cmd import load_raw_config, mask_secrets, validate_dict
        from durin.config.loader import get_config_path
        from durin.config.schema import Config

        raw = load_raw_config(get_config_path())
        try:
            effective = validate_dict(raw).model_dump(mode="json", by_alias=True)
        except Exception:  # noqa: BLE001
            effective = raw
        return ConfigGetResult(
            config=mask_secrets(effective),
            json_schema=Config.model_json_schema(by_alias=True),
        )

    @route(
        "GET",
        "/api/config/set",
        scope=Scope.CONFIG_WRITE.value,
        request_model=ConfigSetCommand,
        response_model=ConfigSetResult,
        summary="Set one dotted config key (schema-validated before write)",
    )
    async def set(self, cmd: ConfigSetCommand, principal: Principal) -> ConfigSetResult:
        principal.require(Scope.CONFIG_WRITE)
        from durin.cli.config_cmd import (
            _normalize_dotted_path,
            load_raw_config,
            mask_secrets,
            parse_value,
            set_at,
            validate_dict,
        )
        from durin.config.loader import get_config_path, save_config

        path = get_config_path()
        try:
            canonical = validate_dict(load_raw_config(path)).model_dump(
                mode="json", by_alias=True
            )
        except Exception as e:  # noqa: BLE001
            raise ValidationFailedError(f"on-disk config is invalid: {e}") from e

        new_data = set_at(canonical, _normalize_dotted_path(cmd.key), parse_value(cmd.value))
        try:
            config = validate_dict(new_data)
        except Exception as e:  # noqa: BLE001
            raise ValidationFailedError(f"validation failed: {e}") from e

        save_config(config, path)
        return ConfigSetResult(
            ok=True,
            config=mask_secrets(config.model_dump(mode="json", by_alias=True)),
        )

    @route(
        "GET",
        "/api/models",
        scope=Scope.CONFIG_READ.value,
        request_model=ModelsListQuery,
        response_model=ModelsListResult,
        summary="Model catalog filtered by provider and/or capability",
    )
    async def models_list(
        self, query: ModelsListQuery, principal: Principal
    ) -> ModelsListResult:
        principal.require(Scope.CONFIG_READ)
        from durin.cli.onboard_wizard import DEFAULT_MODELS
        from durin.providers.registry import find_by_name

        provider = query.provider.strip()
        capability = query.capability.strip().lower()

        if provider in ("openai-codex", "openai_codex"):
            access = None
            try:
                from oauth_cli_kit import get_token
                from oauth_cli_kit.providers import OPENAI_CODEX_PROVIDER

                from durin.providers.codex_device_auth import _strict_storage

                tok = get_token(OPENAI_CODEX_PROVIDER, _strict_storage())
                access = tok.access if tok else None
            except Exception:  # noqa: BLE001
                access = None
            from durin.providers.codex_models import list_codex_models

            models = list_codex_models(access)
            return ModelsListResult(suggested=models, models=models)

        suggested = list(DEFAULT_MODELS.get(provider, ()))

        provider_keywords: tuple[str, ...] = ()
        if provider:
            lookup_name = _PLAN_BASE.get(provider, provider)
            spec = find_by_name(lookup_name)
            if spec is not None:
                provider_keywords = spec.keywords

        def _capability_ok(info: object) -> bool:
            if capability in ("", "text"):
                return True
            if not isinstance(info, dict):
                return False
            if capability == "vision":
                return bool(info.get("supports_vision"))
            if capability == "audio":
                return bool(info.get("supports_audio_input"))
            return True

        def _provider_ok(mid: str) -> bool:
            if not provider_keywords:
                return True
            mid_lower = mid.lower()
            mid_normalized = mid_lower.replace("-", "_")
            for kw in provider_keywords:
                kw_lower = kw.lower()
                if kw_lower in mid_lower or kw_lower.replace("-", "_") in mid_normalized:
                    return True
            return False

        catalog: list[str] = []
        try:
            from durin.providers.capabilities import _load_capabilities_snapshot

            models_data = _load_capabilities_snapshot() or {}
            catalog = sorted(
                mid
                for mid, info in models_data.items()
                if isinstance(mid, str)
                and (
                    not isinstance(info, dict)
                    or info.get("mode") != "image_generation"
                )
                and _capability_ok(info)
                and _provider_ok(mid)
            )
        except Exception:  # noqa: BLE001
            catalog = []

        if capability in ("vision", "audio", "image"):
            try:
                from durin.providers.capabilities import _load_capabilities_snapshot

                snapshot = _load_capabilities_snapshot() or {}
            except Exception:  # noqa: BLE001
                snapshot = {}
            suggested = [
                m for m in suggested
                if m not in snapshot or _capability_ok(snapshot.get(m))
            ]

        return ModelsListResult(suggested=suggested, models=catalog)

    @route(
        "GET",
        "/api/model/capabilities",
        scope=Scope.CONFIG_READ.value,
        request_model=ModelCapabilitiesQuery,
        response_model=ModelCapabilitiesResult,
        summary="Resolve capability metadata for a model id",
    )
    async def model_capabilities(
        self, query: ModelCapabilitiesQuery, principal: Principal
    ) -> ModelCapabilitiesResult:
        principal.require(Scope.CONFIG_READ)
        try:
            from durin.providers.capabilities import get_model_capabilities

            caps = get_model_capabilities(query.model, query.provider)
        except Exception as e:  # noqa: BLE001
            raise ValidationFailedError(f"could not resolve capabilities: {e}") from e
        return ModelCapabilitiesResult(
            model=query.model,
            max_input_tokens=getattr(caps, "max_input_tokens", None),
            supports_vision=bool(getattr(caps, "supports_vision", False)),
            supports_audio_input=bool(getattr(caps, "supports_audio_input", False)),
            supports_function_calling=bool(getattr(caps, "supports_function_calling", False)),
            supports_reasoning=bool(getattr(caps, "supports_reasoning", False)),
        )

    @route(
        "GET",
        "/api/channels",
        scope=Scope.CONFIG_READ.value,
        request_model=ChannelsListQuery,
        response_model=ChannelsListResult,
        summary="Discovered channels with their enabled state and primary credential field",
    )
    async def channels_list(
        self, query: ChannelsListQuery, principal: Principal
    ) -> ChannelsListResult:
        principal.require(Scope.CONFIG_READ)
        from durin.channels.registry import discover_all
        from durin.config.loader import load_config

        config = load_config()
        extra = getattr(config.channels, "__pydantic_extra__", None) or {}
        items: list[dict[str, Any]] = []
        for name, cls in sorted(discover_all().items()):
            section = extra.get(name)
            enabled = (
                bool(section.get("enabled")) if isinstance(section, dict) else False
            )
            credential_field = None
            try:
                defaults = cls.default_config() if hasattr(cls, "default_config") else {}
                credential_field = next(
                    (f for f in _CRED_FIELDS if f in defaults), None
                )
            except Exception:  # noqa: BLE001
                credential_field = None
            items.append(
                {
                    "name": name,
                    "display_name": getattr(cls, "display_name", name),
                    "enabled": enabled,
                    "credential_field": credential_field,
                }
            )
        return ChannelsListResult(channels=items)

    @route(
        "GET",
        "/api/model/test",
        scope=Scope.CONFIG_READ.value,
        request_model=ModelTestQuery,
        response_model=ModelTestResult,
        summary="Live round-trip ping to verify a model/provider combo",
    )
    async def model_test(
        self, query: ModelTestQuery, principal: Principal
    ) -> ModelTestResult:
        principal.require(Scope.CONFIG_READ)
        from durin.cli.doctor import check_model_ping_async
        from durin.config.loader import load_config

        try:
            cfg = load_config()
        except Exception as e:  # noqa: BLE001
            raise ValidationFailedError(f"could not load config: {e}") from e

        model = query.model.strip()
        provider = query.provider.strip()
        if model:
            cfg.agents.defaults.model = model
            cfg.agents.defaults.model_preset = None
        if provider:
            cfg.agents.defaults.provider = provider

        result = await check_model_ping_async(cfg=cfg)
        return ModelTestResult(
            status=result.status,
            message=result.message,
            fix=result.fix or "",
        )

    @route(
        "GET",
        "/api/memory/cross-encoder/test",
        scope=Scope.CONFIG_READ.value,
        request_model=CrossEncoderTestQuery,
        response_model=CrossEncoderTestResult,
        summary="Load and probe a cross-encoder model id (off-thread, may be slow)",
    )
    async def cross_encoder_test(
        self, query: CrossEncoderTestQuery, principal: Principal
    ) -> CrossEncoderTestResult:
        """Probe a cross-encoder model by loading it and running a trivial score.

        The load is potentially slow (model download + warmup).  Run it in a
        thread so the gateway event loop stays responsive, identical to the
        original handler.
        """
        principal.require(Scope.CONFIG_READ)
        import asyncio

        from durin.memory.cross_encoder import probe_model

        try:
            result = await asyncio.to_thread(probe_model, query.model)
        except Exception as exc:  # noqa: BLE001
            return CrossEncoderTestResult(
                status="fail",
                message=f"unexpected error: {type(exc).__name__}: {exc}",
                model_id=query.model,
                duration_ms=0.0,
            )
        return CrossEncoderTestResult(
            status=result["status"],
            message=result["message"],
            model_id=result["model_id"],
            duration_ms=float(result["duration_ms"]),
        )
