"""ConfigService — effective config read/write, model catalog, capabilities, channels,
and async model probes.

Wraps ``durin.config``, ``durin.providers``, ``durin.channels``, and the
``durin.cli.doctor`` / ``durin.memory.cross_encoder`` probe helpers.

Async probes
------------
``model_test`` and ``cross_encoder_test`` are ``async def`` because they perform
genuine I/O (a live model round-trip and a potentially slow model-download+warmup).
Their service methods stay async; the shims ``await`` them. Inside the service,
``cross_encoder_test`` uses ``asyncio.to_thread`` to run the blocking ``probe_model``
call off the event loop — identical to the original handler.

``dict[str, Any]`` escape hatches
----------------------------------
- ``ConfigGetResult.config`` / ``.schema``: the effective config dict and its JSON
  schema are large, dynamic, provider-generated dicts. Typed as ``dict[str, Any]``
  escape hatches; the sub-structure can tighten if it is ever frozen.
- ``ModelsListResult.suggested`` / ``.models``: free-form string lists (``list[str]``
  typed properly).
- ``ModelCapabilitiesResult`` fields are typed scalars (no escape hatch needed).
- ``ChannelsListResult.channels``: list of channel-info dicts (``list[dict[str, Any]]``
  escape hatch — shape comes from the channel registry).

Extracted from ``durin/channels/websocket.py``
(``_handle_config_get`` / ``_handle_config_set`` / ``_handle_models_list`` /
``_handle_model_capabilities`` / ``_handle_channels_list`` / ``_handle_model_test`` /
``_handle_cross_encoder_test``) in SP1; the channel keeps wire-identical shims.
"""

from __future__ import annotations

from typing import Any

from pydantic import Field

from durin.service.principal import Principal, Scope
from durin.service.registry import route
from durin.service.types import (
    Command,
    Query,
    Result,
    ValidationFailedError,
)

# ---------------------------------------------------------------------------
# DTOs — config get
# ---------------------------------------------------------------------------


class ConfigGetQuery(Query):
    """No inputs — returns the full effective config + JSON schema."""


class ConfigGetResult(Result):
    """Full effective config (secrets masked) plus its JSON schema.

    Both fields are ``dict[str, Any]`` escape hatches: the config dict is
    dynamically assembled by pydantic and the schema is generated by
    ``Config.model_json_schema``.

    ``json_schema`` is aliased to ``"schema"`` on the wire because ``schema``
    is a reserved name on ``pydantic.BaseModel``.
    """

    config: dict[str, Any]
    json_schema: dict[str, Any] = Field(alias="schema")  # wire key: "schema"


# ---------------------------------------------------------------------------
# DTOs — config set
# ---------------------------------------------------------------------------


class ConfigSetCommand(Command):
    key: str
    value: str


class ConfigSetResult(Result):
    ok: bool
    config: dict[str, Any]  # escape hatch — full updated config, secrets masked


# ---------------------------------------------------------------------------
# DTOs — models list
# ---------------------------------------------------------------------------


class ModelsListQuery(Query):
    provider: str = ""
    capability: str = ""


class ModelsListResult(Result):
    suggested: list[str]
    models: list[str]


class ModelPickerQuery(Query):
    recent: str = ""


class PickerEntryModel(Result):
    name: str
    provider: str
    group: str
    role: str
    ref: str
    max_input_tokens: int | None = None
    supports_vision: bool = False
    supports_audio_input: bool = False
    supports_reasoning: bool = False


class ModelPickerResult(Result):
    entries: list[PickerEntryModel]


class ProviderModelsQuery(Query):
    provider: str


class ProviderModelEntry(Result):
    id: str
    configured: bool = False
    max_input_tokens: int | None = None
    # Effective (override-or-catalog) capabilities, for the caps badge display.
    supports_vision: bool = False
    supports_audio_input: bool = False
    supports_reasoning: bool = False
    # Raw capability override (None = no override, inheriting catalog/heuristic).
    # Separate from the effective fields above so the editor's tri-state selector
    # can show "inherit" rather than pre-selecting the catalog value as if it were
    # a user override.
    supports_vision_override: bool | None = None
    supports_audio_input_override: bool | None = None
    supports_reasoning_override: bool | None = None
    # User param overrides (None = inherit catalog / default).
    max_tokens: int | None = None
    context_window_tokens: int | None = None
    temperature: float | None = None
    reasoning_effort: str | None = None
    # Sampling params (None = inherit / don't send). top_p is standard;
    # top_k / repeat_penalty are non-standard (sent via extra_body).
    top_p: float | None = None
    top_k: int | None = None
    repeat_penalty: float | None = None


class ProviderModelsResult(Result):
    provider: str
    models: list[ProviderModelEntry]


class ProviderModelUpsertCommand(Command):
    provider: str
    model: str
    max_tokens: int | None = None
    context_window_tokens: int | None = None
    temperature: float | None = None
    reasoning_effort: str | None = None
    top_p: float | None = None
    top_k: int | None = None
    repeat_penalty: float | None = None
    supports_vision: bool | None = None
    supports_audio_input: bool | None = None
    supports_reasoning: bool | None = None


class ProviderModelDeleteCommand(Command):
    provider: str
    model: str


# ---------------------------------------------------------------------------
# DTOs — model capabilities
# ---------------------------------------------------------------------------


class ModelCapabilitiesQuery(Query):
    model: str
    provider: str | None = None


class ModelCapabilitiesResult(Result):
    model: str
    max_input_tokens: int | None
    supports_vision: bool
    supports_audio_input: bool
    supports_function_calling: bool
    supports_reasoning: bool


# ---------------------------------------------------------------------------
# DTOs — channels list
# ---------------------------------------------------------------------------


class ChannelsListQuery(Query):
    """No inputs — lists all discovered channels with their enabled state."""


class ChannelsListResult(Result):
    channels: list[dict[str, Any]]  # escape hatch — shape from channel registry


# ---------------------------------------------------------------------------
# DTOs — model test (async probe)
# ---------------------------------------------------------------------------


class ModelTestQuery(Query):
    model: str = ""
    provider: str = ""


class ModelTestResult(Result):
    status: str
    message: str
    fix: str


# ---------------------------------------------------------------------------
# DTOs — cross-encoder test (async probe)
# ---------------------------------------------------------------------------


class CrossEncoderTestQuery(Query):
    model: str


class CrossEncoderTestResult(Result):
    status: str
    message: str
    model_id: str
    duration_ms: float


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------

#: Credential field names, in priority order (first match wins).
_CRED_FIELDS: tuple[str, ...] = (
    "token", "bot_token", "app_token", "appId", "app_id",
    "api_key", "claw_token", "access_token",
)


def _py_type_name(annotation: Any) -> str:
    """Map a Pydantic field annotation to a webui field type tag."""
    import typing

    origin = typing.get_origin(annotation)
    if annotation is bool:
        return "bool"
    if annotation is int:
        return "int"
    if origin in (list, typing.List):
        return "string_list"
    return "string"


def _channel_field_schema(model: type) -> list[dict[str, Any]]:
    """Build the webui field schema from a Pydantic channel config model."""
    fields: list[dict[str, Any]] = []
    for fname, finfo in model.model_fields.items():
        if fname == "enabled":
            continue  # the toggle is handled separately
        extra = finfo.json_schema_extra or {}
        is_secret = bool(extra.get("secret"))
        group = str(extra.get("group", ""))
        # A field is rendered only if it opts in: it has a group OR is a
        # secret. Email gives every field a group (full form); WebSocket marks
        # only `token` secret, so the rest of its config (host, ssl paths,
        # token_issue_secret, …) stays out of the UI and in config.toml.
        if not group and not is_secret:
            continue
        if finfo.is_required():
            default = None
        else:
            default = finfo.get_default(call_default_factory=True)
            if isinstance(default, (set, frozenset)):
                default = list(default)
        fields.append(
            {
                "name": fname,
                "type": "secret" if is_secret else _py_type_name(finfo.annotation),
                "secret": is_secret,
                "group": group,
                "required": bool(extra.get("required", False)),
                "default": default,
            }
        )
    return fields


class ConfigService:
    """Read/write the effective config, list models/channels, probe model health."""

    @route(
        "GET",
        "/api/v1/config",
        scope=Scope.CONFIG_READ.value,
        request_model=ConfigGetQuery,
        response_model=ConfigGetResult,
        summary="Return effective config (secrets masked) + JSON schema",
    )
    async def get(self, query: ConfigGetQuery, principal: Principal) -> ConfigGetResult:
        principal.require(Scope.CONFIG_READ)
        from durin.cli.config_cmd import load_raw_config, mask_secrets, validate_dict
        from durin.config.loader import get_config_path
        from durin.config.schema import Config

        raw = load_raw_config(get_config_path())
        try:
            effective = validate_dict(raw).model_dump(mode="json", by_alias=False)
        except Exception:  # noqa: BLE001
            effective = raw
        return ConfigGetResult(
            config=mask_secrets(effective),
            json_schema=Config.model_json_schema(by_alias=False),
        )

    @route(
        "POST",
        "/api/v1/config",
        scope=Scope.CONFIG_WRITE.value,
        request_model=ConfigSetCommand,
        response_model=ConfigSetResult,
        summary="Set one dotted config key (schema-validated before write)",
    )
    async def set(self, cmd: ConfigSetCommand, principal: Principal) -> ConfigSetResult:
        principal.require(Scope.CONFIG_WRITE)
        from durin.cli.config_cmd import (
            _normalize_dotted_path,
            load_raw_config,
            mask_secrets,
            parse_value,
            set_at,
            validate_dict,
        )
        from durin.config.loader import get_config_path, save_config

        path = get_config_path()
        try:
            canonical = validate_dict(load_raw_config(path)).model_dump(
                mode="json", by_alias=False
            )
        except Exception as e:  # noqa: BLE001
            raise ValidationFailedError(f"on-disk config is invalid: {e}") from e

        new_data = set_at(canonical, _normalize_dotted_path(cmd.key), parse_value(cmd.value))
        try:
            config = validate_dict(new_data)
        except Exception as e:  # noqa: BLE001
            raise ValidationFailedError(f"validation failed: {e}") from e

        save_config(config, path)
        return ConfigSetResult(
            ok=True,
            config=mask_secrets(config.model_dump(mode="json", by_alias=False)),
        )

    @route(
        "GET",
        "/api/v1/providers/models",
        scope=Scope.CONFIG_READ.value,
        request_model=ProviderModelsQuery,
        response_model=ProviderModelsResult,
        summary="Per-provider catalog models with caps and configured params",
    )
    async def provider_models_route(
        self, query: ProviderModelsQuery, principal: Principal
    ) -> ProviderModelsResult:
        principal.require(Scope.CONFIG_READ)
        from durin.config.loader import load_config
        from durin.providers.provider_catalog import provider_models

        provider = query.provider.strip()
        cfg = load_config()
        pc = getattr(cfg.providers, provider, None)
        configured = dict(getattr(pc, "models", {}) or {})
        cap_overrides = cfg.model_capabilities
        out: list[ProviderModelEntry] = []
        seen: set[str] = set()
        for mi in provider_models(provider):
            seen.add(mi.id)
            ov = configured.get(mi.id)
            cap_ov = cap_overrides.get(f"{provider}/{mi.id}")
            out.append(
                ProviderModelEntry(
                    id=mi.id,
                    configured=mi.id in configured,
                    max_input_tokens=mi.max_input_tokens,
                    supports_vision=(
                        cap_ov.supports_vision if cap_ov and cap_ov.supports_vision is not None
                        else mi.supports_vision
                    ),
                    supports_audio_input=(
                        cap_ov.supports_audio_input if cap_ov and cap_ov.supports_audio_input is not None
                        else mi.supports_audio_input
                    ),
                    supports_reasoning=(
                        cap_ov.supports_reasoning if cap_ov and cap_ov.supports_reasoning is not None
                        else mi.supports_reasoning
                    ),
                    supports_vision_override=getattr(cap_ov, "supports_vision", None),
                    supports_audio_input_override=getattr(cap_ov, "supports_audio_input", None),
                    supports_reasoning_override=getattr(cap_ov, "supports_reasoning", None),
                    max_tokens=getattr(ov, "max_tokens", None),
                    context_window_tokens=getattr(ov, "context_window_tokens", None),
                    temperature=getattr(ov, "temperature", None),
                    reasoning_effort=getattr(ov, "reasoning_effort", None),
                    top_p=getattr(ov, "top_p", None),
                    top_k=getattr(ov, "top_k", None),
                    repeat_penalty=getattr(ov, "repeat_penalty", None),
                )
            )
        for mid, ov in configured.items():  # user customs not in the catalog
            if mid in seen:
                continue
            cap_ov = cap_overrides.get(f"{provider}/{mid}")
            out.append(
                ProviderModelEntry(
                    id=mid, configured=True,
                    supports_vision=(cap_ov.supports_vision if cap_ov and cap_ov.supports_vision is not None else False),
                    supports_audio_input=(cap_ov.supports_audio_input if cap_ov and cap_ov.supports_audio_input is not None else False),
                    supports_reasoning=(cap_ov.supports_reasoning if cap_ov and cap_ov.supports_reasoning is not None else False),
                    supports_vision_override=getattr(cap_ov, "supports_vision", None),
                    supports_audio_input_override=getattr(cap_ov, "supports_audio_input", None),
                    supports_reasoning_override=getattr(cap_ov, "supports_reasoning", None),
                    max_tokens=ov.max_tokens,
                    context_window_tokens=ov.context_window_tokens,
                    temperature=ov.temperature,
                    reasoning_effort=ov.reasoning_effort,
                    top_p=ov.top_p,
                    top_k=ov.top_k,
                    repeat_penalty=ov.repeat_penalty,
                )
            )
        out.sort(key=lambda e: e.id)
        return ProviderModelsResult(provider=provider, models=out)

    @route(
        "POST",
        "/api/v1/providers/model",
        scope=Scope.CONFIG_WRITE.value,
        request_model=ProviderModelUpsertCommand,
        response_model=ConfigSetResult,
        summary="Add or update a configured model's params under a provider",
    )
    async def provider_model_upsert(
        self, cmd: ProviderModelUpsertCommand, principal: Principal
    ) -> ConfigSetResult:
        principal.require(Scope.CONFIG_WRITE)
        from durin.cli.config_cmd import mask_secrets
        from durin.config.loader import get_config_path, load_config, save_config
        from durin.config.schema import ModelEntry

        path = get_config_path()
        cfg = load_config(path)
        pc = getattr(cfg.providers, cmd.provider, None)
        if pc is None:
            raise ValidationFailedError(f"unknown provider {cmd.provider!r}")
        pc.models[cmd.model] = ModelEntry(
            max_tokens=cmd.max_tokens,
            context_window_tokens=cmd.context_window_tokens,
            temperature=cmd.temperature,
            reasoning_effort=cmd.reasoning_effort,
            top_p=cmd.top_p,
            top_k=cmd.top_k,
            repeat_penalty=cmd.repeat_penalty,
        )
        # The three tri-state fields carry the COMPLETE desired override for this
        # model's vision/audio/reasoning (the editor always sends all three): a
        # value sets the override, None clears it back to inherit. Override fields
        # not surfaced by the editor (function calling, token bounds, …) are
        # preserved; the key is dropped when no override remains.
        from durin.config.schema import ModelCapabilityOverride

        cap_key = f"{cmd.provider}/{cmd.model}"
        existing = cfg.model_capabilities.get(cap_key)
        caps = existing.model_dump(exclude_none=True) if existing is not None else {}
        for field, value in (
            ("supports_vision", cmd.supports_vision),
            ("supports_audio_input", cmd.supports_audio_input),
            ("supports_reasoning", cmd.supports_reasoning),
        ):
            if value is None:
                caps.pop(field, None)
            else:
                caps[field] = value
        if caps:
            cfg.model_capabilities[cap_key] = ModelCapabilityOverride(**caps)
        else:
            cfg.model_capabilities.pop(cap_key, None)
        save_config(cfg, path)
        return ConfigSetResult(
            ok=True, config=mask_secrets(cfg.model_dump(mode="json", by_alias=False))
        )

    @route(
        "POST",
        "/api/v1/providers/model/remove",
        scope=Scope.CONFIG_WRITE.value,
        request_model=ProviderModelDeleteCommand,
        response_model=ConfigSetResult,
        summary="Remove a configured model from a provider",
    )
    async def provider_model_remove(
        self, cmd: ProviderModelDeleteCommand, principal: Principal
    ) -> ConfigSetResult:
        principal.require(Scope.CONFIG_WRITE)
        from durin.cli.config_cmd import mask_secrets
        from durin.config.loader import get_config_path, load_config, save_config

        path = get_config_path()
        cfg = load_config(path)
        pc = getattr(cfg.providers, cmd.provider, None)
        changed = False
        if pc is not None and getattr(pc, "models", None):
            changed = pc.models.pop(cmd.model, None) is not None
        # Drop any orphaned capability override so a later re-add starts clean.
        if cfg.model_capabilities.pop(f"{cmd.provider}/{cmd.model}", None) is not None:
            changed = True
        if changed:
            save_config(cfg, path)
        return ConfigSetResult(
            ok=True, config=mask_secrets(cfg.model_dump(mode="json", by_alias=False))
        )

    @route(
        "GET",
        "/api/v1/models",
        scope=Scope.CONFIG_READ.value,
        request_model=ModelsListQuery,
        response_model=ModelsListResult,
        summary="Model catalog filtered by provider and/or capability",
    )
    async def models_list(
        self, query: ModelsListQuery, principal: Principal
    ) -> ModelsListResult:
        principal.require(Scope.CONFIG_READ)

        provider = query.provider.strip()
        capability = query.capability.strip().lower()

        if provider in ("openai-codex", "openai_codex"):
            access = None
            try:
                from oauth_cli_kit import get_token
                from oauth_cli_kit.providers import OPENAI_CODEX_PROVIDER

                from durin.providers.codex_device_auth import _strict_storage

                tok = get_token(OPENAI_CODEX_PROVIDER, _strict_storage())
                access = tok.access if tok else None
            except Exception:  # noqa: BLE001
                access = None
            from durin.providers.codex_models import list_codex_models

            models = list_codex_models(access)
            return ModelsListResult(suggested=models, models=models)

        from durin.config.loader import load_config
        from durin.providers.provider_catalog import provider_models
        from durin.providers.selection import configured_model_ids, configured_provider_names

        def _cap_ok(mi) -> bool:
            if capability in ("", "text"):
                return True
            if capability == "vision":
                return mi.supports_vision
            if capability == "audio":
                return mi.supports_audio_input
            return True

        if provider:
            ids = {mi.id for mi in provider_models(provider) if _cap_ok(mi)}
            if capability in ("", "text"):
                ids.update(configured_model_ids(load_config(), provider))  # user customs
            models = sorted(ids)
            return ModelsListResult(suggested=models, models=models)

        # No provider filter: union of every configured provider's catalog.
        cfg = load_config()
        suggested: list[str] = []
        seen: set[str] = set()
        for pname in sorted(configured_provider_names(cfg)):
            if pname == "custom":
                continue
            for mi in provider_models(pname):
                if mi.id not in seen and _cap_ok(mi):
                    seen.add(mi.id)
                    suggested.append(mi.id)
            if capability in ("", "text"):
                for cid in configured_model_ids(cfg, pname):
                    if cid not in seen:
                        seen.add(cid)
                        suggested.append(cid)
        return ModelsListResult(suggested=suggested, models=suggested)

    @route(
        "GET",
        "/api/v1/model/picker",
        scope=Scope.CONFIG_READ.value,
        request_model=ModelPickerQuery,
        response_model=ModelPickerResult,
        summary="Ordered model picker entries (easy-pick + configured catalog)",
    )
    async def model_picker(
        self, query: ModelPickerQuery, principal: Principal
    ) -> ModelPickerResult:
        principal.require(Scope.CONFIG_READ)
        from durin.agent.model_picker import picker_entries
        from durin.config.loader import load_config

        config = load_config()
        recent = [r for r in query.recent.split(",") if r]
        entries = picker_entries(
            config,
            presets=config.model_presets,
            recent=recent,
            active=config.agents.defaults.model_preset,
        )
        return ModelPickerResult(
            entries=[
                PickerEntryModel(
                    name=e.name, provider=e.provider, group=e.group, role=e.role,
                    ref=e.ref, max_input_tokens=e.max_input_tokens,
                    supports_vision=e.supports_vision,
                    supports_audio_input=e.supports_audio_input,
                    supports_reasoning=e.supports_reasoning,
                )
                for e in entries
            ]
        )

    @route(
        "GET",
        "/api/v1/model/capabilities",
        scope=Scope.CONFIG_READ.value,
        request_model=ModelCapabilitiesQuery,
        response_model=ModelCapabilitiesResult,
        summary="Resolve capability metadata for a model id",
    )
    async def model_capabilities(
        self, query: ModelCapabilitiesQuery, principal: Principal
    ) -> ModelCapabilitiesResult:
        principal.require(Scope.CONFIG_READ)
        try:
            from durin.config.loader import load_config
            from durin.providers.capabilities import get_model_capabilities

            cfg = load_config()
            overrides = {k: v.model_dump(exclude_none=True) for k, v in cfg.model_capabilities.items()}
            caps = get_model_capabilities(query.model, query.provider, overrides=overrides)
        except Exception as e:  # noqa: BLE001
            raise ValidationFailedError(f"could not resolve capabilities: {e}") from e
        return ModelCapabilitiesResult(
            model=query.model,
            max_input_tokens=getattr(caps, "max_input_tokens", None),
            supports_vision=bool(getattr(caps, "supports_vision", False)),
            supports_audio_input=bool(getattr(caps, "supports_audio_input", False)),
            supports_function_calling=bool(getattr(caps, "supports_function_calling", False)),
            supports_reasoning=bool(getattr(caps, "supports_reasoning", False)),
        )

    @route(
        "GET",
        "/api/v1/channels",
        scope=Scope.CONFIG_READ.value,
        request_model=ChannelsListQuery,
        response_model=ChannelsListResult,
        summary="Discovered channels with their enabled state and primary credential field",
    )
    async def channels_list(
        self, query: ChannelsListQuery, principal: Principal
    ) -> ChannelsListResult:
        principal.require(Scope.CONFIG_READ)
        from durin.channels.registry import discover_all
        from durin.config.loader import load_config

        config = load_config()
        extra = getattr(config.channels, "__pydantic_extra__", None) or {}
        items: list[dict[str, Any]] = []
        for name, cls in sorted(discover_all().items()):
            section = extra.get(name)
            enabled = (
                bool(section.get("enabled")) if isinstance(section, dict) else False
            )
            model = cls.config_model() if hasattr(cls, "config_model") else None
            fields: list[dict[str, Any]] = []
            credential_field = None
            if model is not None:
                try:
                    fields = _channel_field_schema(model)
                except Exception:  # noqa: BLE001
                    fields = []
            if not fields:
                try:
                    defaults = cls.default_config() if hasattr(cls, "default_config") else {}
                    credential_field = next(
                        (f for f in _CRED_FIELDS if f in defaults), None
                    )
                except Exception:  # noqa: BLE001
                    credential_field = None
            always_on = name == "websocket" and bool(
                getattr(config.gateway, "webui_enabled", False)
            )
            items.append(
                {
                    "name": name,
                    "display_name": getattr(cls, "display_name", name),
                    "enabled": enabled,
                    "always_on": always_on,
                    "description": getattr(cls, "channel_description", ""),
                    "credential_field": credential_field,
                    "fields": fields,
                }
            )
        return ChannelsListResult(channels=items)

    @route(
        "GET",
        "/api/v1/model/test",
        scope=Scope.CONFIG_READ.value,
        request_model=ModelTestQuery,
        response_model=ModelTestResult,
        summary="Live round-trip ping to verify a model/provider combo",
    )
    async def model_test(
        self, query: ModelTestQuery, principal: Principal
    ) -> ModelTestResult:
        principal.require(Scope.CONFIG_READ)
        from durin.cli.doctor import check_model_ping_async
        from durin.config.loader import load_config

        try:
            cfg = load_config()
        except Exception as e:  # noqa: BLE001
            raise ValidationFailedError(f"could not load config: {e}") from e

        model = query.model.strip()
        provider = query.provider.strip()
        if model:
            cfg.agents.defaults.model = model
            cfg.agents.defaults.model_preset = None
        if provider:
            cfg.agents.defaults.provider = provider

        result = await check_model_ping_async(cfg=cfg)
        return ModelTestResult(
            status=result.status,
            message=result.message,
            fix=result.fix or "",
        )

    @route(
        "GET",
        "/api/v1/memory/cross-encoder/test",
        scope=Scope.CONFIG_READ.value,
        request_model=CrossEncoderTestQuery,
        response_model=CrossEncoderTestResult,
        summary="Load and probe a cross-encoder model id (off-thread, may be slow)",
    )
    async def cross_encoder_test(
        self, query: CrossEncoderTestQuery, principal: Principal
    ) -> CrossEncoderTestResult:
        """Probe a cross-encoder model by loading it and running a trivial score.

        The load is potentially slow (model download + warmup).  Run it in a
        thread so the gateway event loop stays responsive, identical to the
        original handler.
        """
        principal.require(Scope.CONFIG_READ)
        import asyncio

        from durin.memory.cross_encoder import probe_model

        try:
            result = await asyncio.to_thread(probe_model, query.model)
        except Exception as exc:  # noqa: BLE001
            return CrossEncoderTestResult(
                status="fail",
                message=f"unexpected error: {type(exc).__name__}: {exc}",
                model_id=query.model,
                duration_ms=0.0,
            )
        return CrossEncoderTestResult(
            status=result["status"],
            message=result["message"],
            model_id=result["model_id"],
            duration_ms=float(result["duration_ms"]),
        )
