"""Authority-by-context gate for privileged agent actions.

An action that introduces or modifies EXECUTABLE state — an MCP server, a
skill, a dependency install — must not be authorized by a value the model
wrote. A field in a tool call is a claim by the model; it is never evidence
about the world outside it, so a gate that reads ``confirm`` from the call
arguments is not a gate at all.

Authority here is a property of the execution CONTEXT, which the runtime
owns: the session key is generated by the gateway (``websocket:``,
``cron:``, ``workflow:``…), never by the model. Two outcomes:

``allow``   a human is reachable in this context and can see what happens.
``staged``  nobody can be asked (cron, dream, workflow, sub-agent, script).
            The request is recorded under ``<workspace>/.approvals/`` and the
            action does NOT run — the operator resolves it out of band.

Staging rather than refusing matters: an autonomous run that needed something
leaves a durable record instead of losing the work.
"""
from __future__ import annotations

import json
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from durin.utils.atomic_write import atomic_write_text

__all__ = [
    "AUTONOMOUS_SESSION_PREFIXES",
    "Decision",
    "discard_pending",
    "gate",
    "human_reachable",
    "list_pending",
]

# Session-key prefixes the runtime uses for contexts with no person attached.
# Matched as a plain prefix, so entries must include every separator variant
# actually minted (``cron_dream`` has no colon; ``cron:`` does).
AUTONOMOUS_SESSION_PREFIXES: tuple[str, ...] = (
    "cron:", "cron_dream", "system:", "workflow:", "reactive_dream",
    "dream_supervisor", "gateway", "loop:", "subagent:",
)

# Chat-bearing prefixes: a person is on the other end of these. Anything not
# listed is treated as autonomous — an unrecognised context is not a person.
INTERACTIVE_SESSION_PREFIXES: tuple[str, ...] = (
    "websocket:", "cli:", "tui:", "slack:", "discord:", "telegram:",
    "whatsapp:", "matrix:", "email:", "msteams:",
)

_APPROVALS_DIR = ".approvals"


@dataclass(frozen=True, slots=True)
class Decision:
    """Outcome of one gate evaluation. Exactly one flag is True."""

    allow: bool = False
    staged: bool = False
    message: str = ""
    record: dict | None = None


def human_reachable(session_key: str | None) -> bool:
    """True when a person could actually see and answer in this context.

    Requires BOTH a chat-bearing session kind and a live inbound consumer to
    deliver the answer (``pending_answers.can_block``'s process-level flag).
    Unknown session kinds are autonomous: fail closed.
    """
    if not session_key or not session_key.startswith(INTERACTIVE_SESSION_PREFIXES):
        return False
    from durin.agent import pending_answers

    return pending_answers.consumer_active()


def _pending_dir(workspace: Path | str, subsystem: str) -> Path:
    return Path(workspace) / _APPROVALS_DIR / subsystem


def gate(
    workspace: Path | str,
    subsystem: str,
    *,
    action: str,
    summary: str,
    detail: dict[str, Any] | None = None,
    session_key: str | None = None,
) -> Decision:
    """Decide whether *action* may run in the current context.

    ``detail`` is recorded verbatim for the operator's review and is never
    consulted for the decision — a request cannot authorize itself.
    """
    if human_reachable(session_key):
        return Decision(allow=True)
    record = _stage(workspace, subsystem, action=action, summary=summary,
                    detail=detail or {}, session_key=session_key)
    return Decision(
        staged=True,
        record=record,
        message=(
            f"Not run: {summary}. This context has no user to approve it "
            f"(session {session_key or 'unknown'}), so the request was "
            f"recorded for approval as {subsystem}/{record['id']}. Tell the "
            "user it is waiting for them; do not retry."
        ),
    )


def _stage(
    workspace: Path | str,
    subsystem: str,
    *,
    action: str,
    summary: str,
    detail: dict[str, Any],
    session_key: str | None,
) -> dict:
    record = {
        "id": uuid.uuid4().hex[:12],
        "subsystem": subsystem,
        "action": action,
        "summary": summary,
        "detail": detail,
        "session_key": session_key,
        "requested_at": datetime.now(timezone.utc).isoformat(),
        "status": "pending",
    }
    target = _pending_dir(workspace, subsystem)
    target.mkdir(parents=True, exist_ok=True)
    atomic_write_text(target / f"{record['id']}.json",
                      json.dumps(record, indent=2, ensure_ascii=False))
    return record


def list_pending(workspace: Path | str, subsystem: str) -> list[dict]:
    """Pending requests for *subsystem*, oldest first; [] when none."""
    target = _pending_dir(workspace, subsystem)
    if not target.is_dir():
        return []
    out: list[dict] = []
    for path in sorted(target.glob("*.json")):
        try:
            out.append(json.loads(path.read_text(encoding="utf-8")))
        except (OSError, ValueError):
            continue
    out.sort(key=lambda r: r.get("requested_at") or "")
    return out


def discard_pending(workspace: Path | str, subsystem: str, request_id: str) -> bool:
    """Remove one pending request; False when it wasn't there."""
    path = _pending_dir(workspace, subsystem) / f"{request_id}.json"
    try:
        path.unlink()
        return True
    except OSError:
        return False
