"""Authority-by-context gate for privileged agent actions.

An action that introduces or modifies EXECUTABLE state — an MCP server, a
skill, a dependency install — must not be authorized by a value the model
wrote. A field in a tool call is a claim by the model; it is never evidence
about the world outside it, so a gate that reads ``confirm`` from the call
arguments is not a gate at all.

Authority here is a property of the execution CONTEXT, which the runtime
owns: the session key is generated by the gateway (``websocket:``,
``cron:``, ``workflow:``…), never by the model. ``request`` resolves one of
three paths:

``applied``  a judge cleared it, or a person in this chat answered "approve"
             — the request ran and returned its result.
``rejected`` a person in this chat answered "reject".
``pending``  nobody could be asked (autonomous context, or no answer came
             back). The request is recorded under ``<workspace>/.approvals/``
             and the action does NOT run — it is resolved later out of band
             via ``decide``.

Staging rather than refusing matters: an autonomous run that needed something
leaves a durable record instead of losing the work.
"""
from __future__ import annotations

import asyncio
import json
import uuid
from contextvars import ContextVar
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Awaitable, Callable

from durin.agent import approval_store
from durin.agent.approval_executors import (
    ExecDeps,
    Prepared,
    current_hash,
    execute,
)
from durin.utils.atomic_write import atomic_write_text

__all__ = [
    "AUTONOMOUS_SESSION_PREFIXES",
    "Decision",
    "Outcome",
    "decide",
    "discard_pending",
    "gate",
    "human_reachable",
    "can_authorize",
    "is_interactive",
    "list_pending",
    "note_turn_input",
    "outcome_to_tool_result",
    "request",
]

# Session-key prefixes the runtime uses for contexts with no person attached.
# Matched as a plain prefix, so entries must include every separator variant
# actually minted (``cron_dream`` has no colon; ``cron:`` does).
AUTONOMOUS_SESSION_PREFIXES: tuple[str, ...] = (
    "cron:", "cron_dream", "system:", "workflow:", "reactive_dream",
    "dream_supervisor", "gateway", "loop:", "subagent:", "automation:",
)

# Chat-bearing prefixes: a person is on the other end of these. Anything not
# listed is treated as autonomous — an unrecognised context is not a person.
INTERACTIVE_SESSION_PREFIXES: tuple[str, ...] = (
    "websocket:", "cli:", "slack:", "discord:", "telegram:", "whatsapp:",
    "matrix:", "email:", "msteams:", "unified:", "feishu:", "dingtalk:",
    "wecom:", "weixin:", "qq:",
)

_APPROVALS_DIR = ".approvals"


@dataclass(frozen=True, slots=True)
class Decision:
    """Outcome of one gate evaluation. Exactly one flag is True."""

    allow: bool = False
    staged: bool = False
    message: str = ""
    record: dict | None = None


def human_reachable(session_key: str | None) -> bool:
    """True when a person could actually see and answer in this context.

    Requires BOTH a chat-bearing session kind and a live inbound consumer to
    deliver the answer (``pending_answers.can_block``'s process-level flag).
    Unknown session kinds are autonomous: fail closed.
    """
    if not session_key or not session_key.startswith(INTERACTIVE_SESSION_PREFIXES):
        return False
    from durin.agent import pending_answers

    return pending_answers.consumer_active()


def _pending_dir(workspace: Path | str, subsystem: str) -> Path:
    return Path(workspace) / _APPROVALS_DIR / subsystem


# Set for the rest of a turn once any of its input came from an API token
# rather than a person at a chat surface. A token holder is a program: a
# ``chat:write`` token may converse in a webui conversation, but it must not
# carry the person's authority to approve privileged actions there. Turns run
# in their own task, so the flag never outlives the turn that set it.
_TURN_HAS_API_INPUT: ContextVar[bool] = ContextVar("approval_turn_has_api_input", default=False)


def note_turn_input(metadata: dict[str, Any] | None) -> None:
    """Record that the current turn received input from *metadata*'s sender.

    Called for the message that opens a turn and for every message injected
    into it; input marked ``origin: "api"`` makes ``gate`` stage privileged
    actions for the rest of the turn."""
    if metadata and metadata.get("origin") == "api":
        _TURN_HAS_API_INPUT.set(True)


def can_authorize(session_key: str | None) -> bool:
    """True when the current turn may approve a privileged action itself.

    That takes a person reachable in this context (``human_reachable``) and a
    turn with no input from an API token. Privileged tools decide with this;
    waiting for an answer (``ask_user``) only needs ``human_reachable``, so an
    API client can still answer a question."""
    return human_reachable(session_key) and not _TURN_HAS_API_INPUT.get()


def gate(
    workspace: Path | str,
    subsystem: str,
    *,
    action: str,
    summary: str,
    detail: dict[str, Any] | None = None,
    session_key: str | None = None,
) -> Decision:
    """Decide whether *action* may run in the current context.

    ``detail`` is recorded verbatim for the operator's review and is never
    consulted for the decision — a request cannot authorize itself.
    """
    if can_authorize(session_key):
        return Decision(allow=True)
    record = _stage(workspace, subsystem, action=action, summary=summary,
                    detail=detail or {}, session_key=session_key)
    why = (
        "This turn includes input from an API token, which cannot approve it"
        if human_reachable(session_key)
        else f"This context has no user to approve it (session {session_key or 'unknown'})"
    )
    return Decision(
        staged=True,
        record=record,
        message=(
            f"Not run: {summary}. {why}, so the request was recorded for "
            f"approval as {subsystem}/{record['id']}. Tell the user it is "
            "waiting for them; do not retry."
        ),
    )


def _stage(
    workspace: Path | str,
    subsystem: str,
    *,
    action: str,
    summary: str,
    detail: dict[str, Any],
    session_key: str | None,
) -> dict:
    record = {
        "id": uuid.uuid4().hex[:12],
        "subsystem": subsystem,
        "action": action,
        "summary": summary,
        "detail": detail,
        "session_key": session_key,
        "requested_at": datetime.now(timezone.utc).isoformat(),
        "status": "pending",
    }
    target = _pending_dir(workspace, subsystem)
    target.mkdir(parents=True, exist_ok=True)
    atomic_write_text(target / f"{record['id']}.json",
                      json.dumps(record, indent=2, ensure_ascii=False))
    return record


def list_pending(workspace: Path | str, subsystem: str) -> list[dict]:
    """Pending requests for *subsystem*, oldest first; [] when none."""
    target = _pending_dir(workspace, subsystem)
    if not target.is_dir():
        return []
    out: list[dict] = []
    for path in sorted(target.glob("*.json")):
        try:
            out.append(json.loads(path.read_text(encoding="utf-8")))
        except (OSError, ValueError):
            continue
    out.sort(key=lambda r: r.get("requested_at") or "")
    return out


def discard_pending(workspace: Path | str, subsystem: str, request_id: str) -> bool:
    """Remove one pending request; False when it wasn't there."""
    path = _pending_dir(workspace, subsystem) / f"{request_id}.json"
    try:
        path.unlink()
        return True
    except OSError:
        return False


JudgeFn = Callable[[], Awaitable[str | None]]
AskFn = Callable[[dict], Awaitable[str | None]]


@dataclass(frozen=True)
class Outcome:
    status: str  # applied | rejected | pending | failed | stale | refused
    record: dict | None = None
    result: dict | None = None
    message: str = ""


def is_interactive(session_key: str | None) -> bool:
    """A chat-bearing session kind (a person is on the other end)."""
    return bool(session_key) and session_key.startswith(INTERACTIVE_SESSION_PREFIXES)


async def _run_approved(workspace: Path | str, record: dict, deps: ExecDeps) -> Outcome:
    """Execute a record already in ``approved``: re-check its hash, run it once."""
    try:
        now_hash = current_hash(Path(workspace), record)
    except Exception as exc:  # noqa: BLE001 — any hash failure ends the record, never hangs it
        rec = approval_store.transition(workspace, record["id"], expect=("approved",),
                                        to="failed", result={"error": str(exc)})
        return Outcome("failed", rec, None, f"Could not run {record['summary']}: {exc}")
    if now_hash != record.get("change_hash"):
        rec = approval_store.transition(workspace, record["id"], expect=("approved",), to="stale")
        return Outcome("stale", rec, None,
                       f"Not run: {record['summary']} — the target changed after it was "
                       "requested, so the approval no longer matches it. Ask again if still needed.")
    # Executors record who approved (commit trailers, audit log) from here.
    deps.extra["approval"] = {"id": record["id"], "decided_by": record.get("decided_by")}
    try:
        result = await execute(Path(workspace), record, deps)
    except asyncio.CancelledError:
        # A cancelled run must not leave the record stuck in "approved" —
        # nothing else ever retries or expires that state.
        approval_store.transition(workspace, record["id"], expect=("approved",),
                                  to="failed", result={"error": "cancelled"})
        raise
    except Exception as exc:  # noqa: BLE001 — a failed run is recorded, never raised to the turn
        rec = approval_store.transition(workspace, record["id"], expect=("approved",),
                                        to="failed", result={"error": str(exc)})
        return Outcome("failed", rec, None, f"Approved, but running it failed: {exc}")
    rec = approval_store.transition(workspace, record["id"], expect=("approved",),
                                    to="applied", result=result)
    return Outcome("applied", rec, result, f"Done: {record['summary']}.")


def _pending_outcome(record: dict, *, asked: bool) -> Outcome:
    where = ("waiting for approval (`durin approvals`)" if not asked
             else "the user did not answer; it is still waiting for approval (`durin approvals`)")
    return Outcome("pending", record, None, (
        f"Not done yet: {record['summary']} — {where}, id {record['id']}. Continue "
        "without it; do not retry, and do not reach the same effect another way."))


async def request(workspace: Path | str, prepared: Prepared, *, session_key: str | None,
                  deps: ExecDeps, judge: JudgeFn | None = None,
                  ask: AskFn | None = None) -> Outcome:
    """Decide and, when allowed, run one privileged request.

    Order: the judge (when the caller made the request judge-eligible) may clear
    it; otherwise a person in this chat is asked (``ask``); otherwise it is
    filed as pending. Nothing here reads a value the model wrote.
    """
    context = "interactive" if is_interactive(session_key) else "autonomous"
    if prepared.kind in ("skill_deps", "mcp_change", "exec_command"):
        # The judge only ever clears skill installs/edits; deps, MCP changes
        # and exec commands always need a person or end up pending.
        judge = None
    if judge is not None:
        verdict = None
        try:
            verdict = await judge()
        except Exception:  # noqa: BLE001 — an unavailable judge falls through to a person
            verdict = None
        if verdict == "safe":
            existing = approval_store.find_pending(
                workspace, session_key=session_key, kind=prepared.kind,
                change_hash=prepared.change_hash)
            if existing is not None:
                record = approval_store.transition(
                    workspace, existing["id"], expect=("pending",), to="approved",
                    decided_by={"kind": "judge"})
                if record is None:
                    return _already_decided(workspace, existing["id"])
            else:
                record = approval_store.create(
                    workspace, kind=prepared.kind, summary=prepared.summary,
                    detail=prepared.detail, payload=prepared.payload,
                    change_hash=prepared.change_hash, session_key=session_key,
                    context=context, status="approved", decided_by={"kind": "judge"})
            return await _run_approved(workspace, record, deps)

    record = approval_store.find_pending(
        workspace, session_key=session_key, kind=prepared.kind,
        change_hash=prepared.change_hash) or approval_store.create(
        workspace, kind=prepared.kind, summary=prepared.summary, detail=prepared.detail,
        payload=prepared.payload, change_hash=prepared.change_hash,
        session_key=session_key, context=context)

    if ask is None:
        return _pending_outcome(record, asked=False)
    answer = await ask(record)
    if answer not in ("approve", "reject"):
        return _pending_outcome(record, asked=True)
    return await _apply_decision(workspace, record["id"], answer,
                                 decided_by={"kind": "user", "channel": session_key},
                                 deps=deps)


async def _apply_decision(workspace: Path | str, approval_id: str, decision: str, *,
                          decided_by: dict, deps: ExecDeps) -> Outcome:
    if decision == "reject":
        rec = approval_store.transition(workspace, approval_id, expect=("pending",),
                                        to="rejected", decided_by=decided_by)
        if rec is None:
            return _already_decided(workspace, approval_id)
        return Outcome("rejected", rec, None, (
            f"The user declined: {rec['summary']}. Do not retry, and do not reach the "
            "same effect another way."))
    if decision != "approve":
        return Outcome("refused", None, None, f"Unknown decision {decision!r}.")
    rec = approval_store.transition(workspace, approval_id, expect=("pending",),
                                    to="approved", decided_by=decided_by)
    if rec is None:
        return _already_decided(workspace, approval_id)
    return await _run_approved(workspace, rec, deps)


def _already_decided(workspace: Path | str, approval_id: str) -> Outcome:
    rec = approval_store.get(workspace, approval_id)
    if rec is None:
        return Outcome("refused", None, None, f"No approval request {approval_id}.")
    return Outcome("refused", rec, None,
                   f"Approval {approval_id} was already decided ({rec.get('status')}).")


async def decide(workspace: Path | str, approval_id: str, decision: str, *,
                 decided_by: dict, deps: ExecDeps) -> Outcome:
    """Resolve a request from outside the turn that filed it (Pending, CLI, API,
    a webui click). If that turn is still waiting on it, hand the verdict to the
    waiter so the turn runs it and continues. Otherwise decide and run here."""
    if decision not in ("approve", "reject"):
        return Outcome("refused", None, None, f"Unknown decision {decision!r}.")
    rec = approval_store.get(workspace, approval_id)
    if rec is None:
        return Outcome("refused", None, None, f"No approval request {approval_id}.")
    if rec.get("legacy"):
        return Outcome("refused", rec, None, (
            f"{approval_id} is a legacy request with no recorded payload; it can only "
            "be discarded. Ask the agent to request it again."))
    session_key = rec.get("requested_by_session")
    from durin.agent import pending_answers

    if session_key and pending_answers.waiting_ref(session_key) == approval_id:
        if pending_answers.resolve(session_key, decision):
            return Outcome("pending", rec, None, "Handed to the waiting turn.")
    return await _apply_decision(workspace, approval_id, decision,
                                 decided_by=decided_by, deps=deps)


def outcome_to_tool_result(outcome: Outcome) -> dict:
    """What a gated tool returns to the model."""
    out: dict = {"status": outcome.status, "message": outcome.message}
    if outcome.record is not None:
        out["approval_id"] = outcome.record.get("id")
    if outcome.result is not None:
        out["result"] = outcome.result
    return out
