/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API token metadata (no hashes or plaintexts) */
        get: operations["auth_list_tokens"];
        put?: never;
        /** Issue a new API token (plaintext returned once) */
        post: operations["auth_issue_token"];
        /** Revoke an API token by id */
        delete: operations["auth_revoke_token"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discovered channels with their enabled state and primary credential field */
        get: operations["config_channels_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List built-in command palette entries */
        get: operations["commands_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return effective config (secrets masked) + JSON schema */
        get: operations["config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Set one dotted config key (schema-validated before write) */
        get: operations["config_set"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all scheduled jobs (including disabled and system jobs) */
        get: operations["cron_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Remove a non-system cron job by id */
        get: operations["cron_remove"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manually trigger a cron job now (non-blocking) */
        get: operations["cron_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enable or disable a cron job without removing it */
        get: operations["cron_toggle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extras/ensure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Install a pip extra (off-loop); signal whether a restart is needed */
        get: operations["health_extras_ensure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extras/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unconditionally restart the gateway daemon */
        get: operations["health_extras_restart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extras/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is a pip extra installed + what would installing it cost */
        get: operations["health_extras_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read JSONL log segments (gateway or telemetry) with pagination */
        get: operations["health_logs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/backlinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entries that reference the given URI */
        get: operations["memory_backlinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/cross-encoder/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load and probe a cross-encoder model id (off-thread, may be slow) */
        get: operations["config_cross_encoder_test"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/edge/{a}/{b}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entries co-mentioning both refs (edge evidence) */
        get: operations["memory_edge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/entity/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full entity page + history + archive + entries */
        get: operations["memory_entity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/entry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One entry's frontmatter + body */
        get: operations["memory_entry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/forget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Archive a memory entry */
        get: operations["memory_forget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity-centric memory as nodes + edges (graph view) */
        get: operations["memory_graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory search — same shape as the memory_search LLM tool */
        get: operations["memory_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/session/{stem}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session detail for the graph view */
        get: operations["memory_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/subgraph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ego-graph: a node + its N-hop neighbourhood */
        get: operations["memory_subgraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve capability metadata for a model id */
        get: operations["config_model_capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live round-trip ping to verify a model/provider combo */
        get: operations["config_model_test"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model catalog filtered by provider and/or capability */
        get: operations["config_models_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/codex/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disconnect the Codex OAuth session */
        get: operations["oauth_disconnect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/codex/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll the device-code flow for completion */
        get: operations["oauth_poll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/codex/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Request a device-code challenge for Codex OAuth */
        get: operations["oauth_start"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/codex/start-loopback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start the loopback PKCE login (localhost-only) */
        get: operations["oauth_start_loopback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/codex/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return Codex OAuth connection status */
        get: operations["oauth_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List secret metadata (values never returned) */
        get: operations["secrets_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secrets/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delete a secret by name */
        get: operations["secrets_delete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List websocket-channel sessions (path field stripped) */
        get: operations["sessions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{key}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delete a websocket-channel session and its webui thread */
        get: operations["sessions_delete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{key}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return unsigned session JSONL payload (shim applies media signing) */
        get: operations["sessions_messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{key}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Set a user-edited title for a websocket-channel session */
        get: operations["sessions_rename"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{key}/webui-thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate key; shim calls build_webui_thread_response with signing callback */
        get: operations["sessions_webui_thread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the full settings payload (secrets masked) */
        get: operations["settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/provider/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Update provider API key and/or base URL (key stored as secret ref) */
        get: operations["settings_provider_update"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Update agent model and/or provider */
        get: operations["settings_update"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/web-search/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Update web-search provider and credentials */
        get: operations["settings_web_search_update"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List installed skills + store HEAD */
        get: operations["skills_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/describe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lazy SKILL.md description peek (async off-thread) */
        get: operations["skills_describe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/github-token-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify a GitHub-token secret */
        get: operations["skills_github_token_test"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one candidate to quarantine + scan */
        get: operations["skills_import_skill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List skills awaiting an import decision */
        get: operations["skills_quarantine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List candidates a source points at */
        get: operations["skills_resolve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search configured registries (async off-thread) */
        get: operations["skills_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a skill's mode + SKILL.md content */
        get: operations["skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approve a quarantined skill */
        get: operations["skills_approve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one skill file */
        get: operations["skills_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/file/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Save one text file in a skill (manual) */
        get: operations["skills_file_save"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a skill's files */
        get: operations["skills_files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provenance + attributed commit log */
        get: operations["skills_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/install-deps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Install deps for a skill */
        get: operations["skills_install_deps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/judge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run the LLM judge on-demand (async off-thread) */
        get: operations["skills_judge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Set a skill's mode (auto|manual) */
        get: operations["skills_mode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discard a quarantined skill */
        get: operations["skills_reject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delete a workspace skill / revert a fork */
        get: operations["skills_remove"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overwrite a MANUAL skill */
        get: operations["skills_save"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChannelsListQuery
         * @description No inputs — lists all discovered channels with their enabled state.
         */
        ChannelsListQuery: Record<string, never>;
        /** ChannelsListResult */
        ChannelsListResult: {
            /** Channels */
            channels: {
                [key: string]: unknown;
            }[];
        };
        /**
         * CommandsListQuery
         * @description No inputs.
         */
        CommandsListQuery: Record<string, never>;
        /** CommandsResult */
        CommandsResult: {
            /** Commands */
            commands: unknown[];
        };
        /**
         * ConfigGetQuery
         * @description No inputs — returns the full effective config + JSON schema.
         */
        ConfigGetQuery: Record<string, never>;
        /**
         * ConfigGetResult
         * @description Full effective config (secrets masked) plus its JSON schema.
         *
         *     Both fields are ``dict[str, Any]`` escape hatches: the config dict is
         *     dynamically assembled by pydantic and the schema is generated by
         *     ``Config.model_json_schema``.
         *
         *     ``json_schema`` is aliased to ``"schema"`` on the wire because ``schema``
         *     is a reserved name on ``pydantic.BaseModel``.
         */
        ConfigGetResult: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Schema */
            schema: {
                [key: string]: unknown;
            };
        };
        /** ConfigSetCommand */
        ConfigSetCommand: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** ConfigSetResult */
        ConfigSetResult: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Ok */
            ok: boolean;
        };
        /** CronJobItem */
        CronJobItem: {
            /** Channel */
            channel: string;
            /** Createdatms */
            createdAtMs: number;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Issystem */
            isSystem: boolean;
            /** Message */
            message: string;
            /** Name */
            name: string;
            schedule: components["schemas"]["CronJobScheduleResult"];
            state: components["schemas"]["CronJobStateResult"];
            /** Updatedatms */
            updatedAtMs: number;
        };
        /** CronJobScheduleResult */
        CronJobScheduleResult: {
            /** Atms */
            atMs: number | null;
            /** Everyms */
            everyMs: number | null;
            /** Expr */
            expr: string | null;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Tz */
            tz: string | null;
        };
        /** CronJobStateResult */
        CronJobStateResult: {
            /** Executing */
            executing: boolean;
            /** Lasterror */
            lastError: string | null;
            /** Lastrunatms */
            lastRunAtMs: number | null;
            /** Laststatus */
            lastStatus: string | null;
            /** Nextrunatms */
            nextRunAtMs: number | null;
        };
        /**
         * CronListQuery
         * @description No inputs — lists all jobs including disabled ones.
         */
        CronListQuery: Record<string, never>;
        /** CronListResult */
        CronListResult: {
            /** Jobs */
            jobs: components["schemas"]["CronJobItem"][];
        };
        /** CronRemoveCommand */
        CronRemoveCommand: {
            /** Id */
            id: string;
        };
        /** CronRemoveResult */
        CronRemoveResult: {
            /** Result */
            result: string;
        };
        /** CronRunCommand */
        CronRunCommand: {
            /** Id */
            id: string;
        };
        /** CronRunResult */
        CronRunResult: {
            /**
             * Reason
             * @default null
             */
            reason: string | null;
            /** Started */
            started: boolean;
        };
        /** CronToggleCommand */
        CronToggleCommand: {
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
        };
        /** CronToggleResult */
        CronToggleResult: {
            job: components["schemas"]["CronJobItem"];
        };
        /** CrossEncoderTestQuery */
        CrossEncoderTestQuery: {
            /** Model */
            model: string;
        };
        /** CrossEncoderTestResult */
        CrossEncoderTestResult: {
            /** Durationms */
            durationMs: number;
            /** Message */
            message: string;
            /** Modelid */
            modelId: string;
            /** Status */
            status: string;
        };
        /** ExtrasEnsureCommand */
        ExtrasEnsureCommand: {
            /** Feature */
            feature: string;
            /**
             * Restart
             * @default false
             */
            restart: boolean;
        };
        /** ExtrasEnsureResult */
        ExtrasEnsureResult: {
            /** Message */
            message: string;
            /** Needsrestart */
            needsRestart: boolean;
            /**
             * Restarting
             * @default false
             */
            restarting: boolean;
            /** Status */
            status: string;
        };
        /**
         * ExtrasRestartCommand
         * @description No inputs — unconditional restart.
         */
        ExtrasRestartCommand: Record<string, never>;
        /** ExtrasRestartResult */
        ExtrasRestartResult: {
            /** Restarting */
            restarting: boolean;
        };
        /** ExtrasStatusQuery */
        ExtrasStatusQuery: {
            /** Feature */
            feature: string;
        };
        /** ExtrasStatusResult */
        ExtrasStatusResult: {
            /** Approxsize */
            approxSize: string;
            /** Extra */
            extra: string;
            /** Label */
            label: string;
            /** Needsrestart */
            needsRestart: boolean;
            /** Present */
            present: boolean;
        };
        /**
         * ForgetResult
         * @description Result of an archive operation.  ``result`` drives HTTP status.
         */
        ForgetResult: {
            /** Result */
            result: string;
        };
        /** GithubTokenTestQuery */
        GithubTokenTestQuery: {
            /** Secret */
            secret: string;
        };
        /** IssueTokenCommand */
        IssueTokenCommand: {
            /**
             * Label
             * @default
             */
            label: string;
            /** Scopes */
            scopes: string[];
            /**
             * Ttls
             * @default null
             */
            ttlS: number | null;
        };
        /** IssueTokenResult */
        IssueTokenResult: {
            /** Expiresat */
            expiresAt: number | null;
            /** Scopes */
            scopes: string[];
            /** Token */
            token: string;
            /** Tokenid */
            tokenId: string;
        };
        /**
         * ListTokensQuery
         * @description No inputs — list all token metadata.
         */
        ListTokensQuery: Record<string, never>;
        /** ListTokensResult */
        ListTokensResult: {
            /** Tokens */
            tokens: components["schemas"]["TokenMetadata"][];
        };
        /** LogsListQuery */
        LogsListQuery: {
            /**
             * Beforets
             * @default null
             */
            beforeTs: number | null;
            /**
             * Channel
             * @default []
             */
            channel: string[];
            /**
             * Level
             * @default []
             */
            level: string[];
            /**
             * Limit
             * @default 200
             */
            limit: number;
            /**
             * Q
             * @default null
             */
            q: string | null;
            /**
             * Session
             * @default []
             */
            session: string[];
            /**
             * Source
             * @default gateway
             */
            source: string;
            /**
             * Type
             * @default []
             */
            type: string[];
            /**
             * Windowhours
             * @default 24
             */
            windowHours: number | null;
        };
        /** LogsListResult */
        LogsListResult: {
            /** Facets */
            facets: {
                [key: string]: unknown;
            };
            /** Hasmore */
            hasMore: boolean;
            /** Lines */
            lines: unknown[];
            /** Nextcursor */
            nextCursor: unknown;
            /** Scannedthroughts */
            scannedThroughTs: unknown;
        };
        /** MemoryBacklinksQuery */
        MemoryBacklinksQuery: {
            /** Uri */
            uri: string;
        };
        /** MemoryEdgeQuery */
        MemoryEdgeQuery: {
            /** A */
            a: string;
            /** B */
            b: string;
        };
        /** MemoryEntityQuery */
        MemoryEntityQuery: {
            /** Ref */
            ref: string;
        };
        /** MemoryEntryQuery */
        MemoryEntryQuery: {
            /** Uri */
            uri: string;
        };
        /** MemoryForgetCommand */
        MemoryForgetCommand: {
            /** Uri */
            uri: string;
        };
        /**
         * MemoryGraphQuery
         * @description No inputs — returns the full entity graph.
         */
        MemoryGraphQuery: Record<string, never>;
        /**
         * MemoryResult
         * @description Carries a raw graph-api payload dict (escape hatch).
         */
        MemoryResult: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** MemorySearchQuery */
        MemorySearchQuery: {
            /**
             * Kinds
             * @default all
             */
            kinds: string;
            /**
             * Level
             * @default warm
             */
            level: string;
            /** Q */
            q: string;
            /**
             * Scope
             * @default all
             */
            scope: string;
        };
        /** MemorySessionQuery */
        MemorySessionQuery: {
            /** Stem */
            stem: string;
        };
        /** MemorySubgraphQuery */
        MemorySubgraphQuery: {
            /**
             * Hops
             * @default 1
             */
            hops: number;
            /** Ref */
            ref: string;
        };
        /** ModelCapabilitiesQuery */
        ModelCapabilitiesQuery: {
            /** Model */
            model: string;
            /**
             * Provider
             * @default null
             */
            provider: string | null;
        };
        /** ModelCapabilitiesResult */
        ModelCapabilitiesResult: {
            /** Maxinputtokens */
            maxInputTokens: number | null;
            /** Model */
            model: string;
            /** Supportsaudioinput */
            supportsAudioInput: boolean;
            /** Supportsfunctioncalling */
            supportsFunctionCalling: boolean;
            /** Supportsreasoning */
            supportsReasoning: boolean;
            /** Supportsvision */
            supportsVision: boolean;
        };
        /** ModelTestQuery */
        ModelTestQuery: {
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Provider
             * @default
             */
            provider: string;
        };
        /** ModelTestResult */
        ModelTestResult: {
            /** Fix */
            fix: string;
            /** Message */
            message: string;
            /** Status */
            status: string;
        };
        /** ModelsListQuery */
        ModelsListQuery: {
            /**
             * Capability
             * @default
             */
            capability: string;
            /**
             * Provider
             * @default
             */
            provider: string;
        };
        /** ModelsListResult */
        ModelsListResult: {
            /** Models */
            models: string[];
            /** Suggested */
            suggested: string[];
        };
        /**
         * OAuthDisconnectCommand
         * @description Command for ``GET /api/oauth/codex/disconnect``.
         */
        OAuthDisconnectCommand: Record<string, never>;
        /**
         * OAuthPollQuery
         * @description Query for ``GET /api/oauth/codex/poll``.
         */
        OAuthPollQuery: {
            /** Deviceauthid */
            deviceAuthId: string;
            /** Usercode */
            userCode: string;
        };
        /**
         * OAuthPollResult
         * @description Poll tick result.
         *
         *     ``status`` is one of ``"pending"`` | ``"ok"`` | ``"error"``.
         *     When ``status == "ok"`` the connected-session fields are also present.
         */
        OAuthPollResult: {
            /**
             * Connected
             * @default null
             */
            connected: boolean | null;
            /**
             * Email
             * @default null
             */
            email: string | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Plan
             * @default null
             */
            plan: string | null;
            /**
             * Source
             * @default null
             */
            source: string | null;
            /** Status */
            status: string;
        };
        /**
         * OAuthStartCommand
         * @description Command for ``GET /api/oauth/codex/start`` (device-code flow).
         */
        OAuthStartCommand: Record<string, never>;
        /**
         * OAuthStartLoopbackCommand
         * @description Command for ``GET /api/oauth/codex/start-loopback``.
         *
         *     ``is_local`` gates the loopback flow — the service raises ``ForbiddenError``
         *     if False.
         */
        OAuthStartLoopbackCommand: {
            /**
             * Islocal
             * @default false
             */
            isLocal: boolean;
        };
        /** OAuthStartLoopbackResult */
        OAuthStartLoopbackResult: {
            /** Authorizeurl */
            authorizeUrl: string;
        };
        /** OAuthStartResult */
        OAuthStartResult: {
            /** Deviceauthid */
            deviceAuthId: string;
            /** Expiresin */
            expiresIn: number;
            /** Interval */
            interval: number;
            /** Usercode */
            userCode: string;
            /** Verificationuri */
            verificationUri: string;
        };
        /**
         * OAuthStatusQuery
         * @description Query for ``GET /api/oauth/codex/status``.
         *
         *     ``is_local`` — True when the HTTP request arrived via localhost — is used
         *     to populate ``can_loopback`` in the response.
         */
        OAuthStatusQuery: {
            /**
             * Islocal
             * @default false
             */
            isLocal: boolean;
        };
        /** OAuthStatusResult */
        OAuthStatusResult: {
            /**
             * Canloopback
             * @default false
             */
            canLoopback: boolean;
            /** Connected */
            connected: boolean;
            /**
             * Email
             * @default null
             */
            email: string | null;
            /**
             * Plan
             * @default null
             */
            plan: string | null;
            /**
             * Source
             * @default null
             */
            source: string | null;
        };
        /** RevokeTokenCommand */
        RevokeTokenCommand: {
            /** Tokenid */
            tokenId: string;
        };
        /** RevokeTokenResult */
        RevokeTokenResult: {
            /** Ok */
            ok: boolean;
        };
        /** SecretDeleteCommand */
        SecretDeleteCommand: {
            /** Name */
            name: string;
        };
        /** SecretDeleteResult */
        SecretDeleteResult: {
            /** Ok */
            ok: boolean;
        };
        /** SecretItem */
        SecretItem: {
            /** Account */
            account: string;
            /** Createdat */
            createdAt: string;
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Origin */
            origin: string;
            /** Scope */
            scope: string[];
            /** Service */
            service: string;
            /** Valuehint */
            valueHint: string | null;
        };
        /**
         * SecretsListQuery
         * @description No inputs — lists all secret metadata.
         */
        SecretsListQuery: Record<string, never>;
        /** SecretsListResult */
        SecretsListResult: {
            /** Secrets */
            secrets: components["schemas"]["SecretItem"][];
        };
        /** SessionDeleteCommand */
        SessionDeleteCommand: {
            /** Key */
            key: string;
        };
        /** SessionDeleteResult */
        SessionDeleteResult: {
            /** Deleted */
            deleted: boolean;
        };
        /** SessionMessagesQuery */
        SessionMessagesQuery: {
            /** Key */
            key: string;
        };
        /** SessionMessagesResult */
        SessionMessagesResult: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** SessionRenameCommand */
        SessionRenameCommand: {
            /** Key */
            key: string;
            /** Title */
            title: string;
        };
        /** SessionRenameResult */
        SessionRenameResult: {
            /** Title */
            title: string;
        };
        /**
         * SessionsListQuery
         * @description No inputs — lists all websocket-channel sessions.
         */
        SessionsListQuery: Record<string, never>;
        /** SessionsListResult */
        SessionsListResult: {
            /** Sessions */
            sessions: {
                [key: string]: unknown;
            }[];
        };
        /** SettingsProviderUpdateCommand */
        SettingsProviderUpdateCommand: {
            /**
             * Apibase
             * @default null
             */
            apiBase: string | null;
            /**
             * Apikey
             * @default null
             */
            apiKey: string | null;
            /** Provider */
            provider: string;
        };
        /**
         * SettingsQuery
         * @description No inputs — returns the full settings payload.
         */
        SettingsQuery: Record<string, never>;
        /**
         * SettingsResult
         * @description Full settings payload.
         *
         *     ``agent``, ``providers``, ``web_search``, and ``runtime`` mirror the keys
         *     the existing handler returns.  The nested structures are ``dict[str, Any]``
         *     escape hatches — SP3 can tighten them.
         */
        SettingsResult: {
            /** Agent */
            agent: {
                [key: string]: unknown;
            };
            /** Providers */
            providers: {
                [key: string]: unknown;
            }[];
            /** Requiresrestart */
            requiresRestart: boolean;
            /** Runtime */
            runtime: {
                [key: string]: unknown;
            };
            /** Websearch */
            webSearch: {
                [key: string]: unknown;
            };
        };
        /** SettingsUpdateCommand */
        SettingsUpdateCommand: {
            /**
             * Model
             * @default null
             */
            model: string | null;
            /**
             * Provider
             * @default null
             */
            provider: string | null;
        };
        /** SettingsWebSearchUpdateCommand */
        SettingsWebSearchUpdateCommand: {
            /**
             * Apikey
             * @default null
             */
            apiKey: string | null;
            /**
             * Baseurl
             * @default null
             */
            baseUrl: string | null;
            /** Provider */
            provider: string;
        };
        /** SkillApproveCommand */
        SkillApproveCommand: {
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /**
             * Installdeps
             * @default false
             */
            installDeps: boolean;
            /** Name */
            name: string;
            /**
             * Override
             * @default false
             */
            override: boolean;
            /**
             * Replace
             * @default false
             */
            replace: boolean;
        };
        /** SkillDescribeQuery */
        SkillDescribeQuery: {
            /** Ref */
            ref: string;
        };
        /** SkillFileQuery */
        SkillFileQuery: {
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** SkillFileSaveCommand */
        SkillFileSaveCommand: {
            /** Content */
            content: string;
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** SkillFilesQuery */
        SkillFilesQuery: {
            /** Name */
            name: string;
        };
        /** SkillGetQuery */
        SkillGetQuery: {
            /** Name */
            name: string;
        };
        /** SkillHistoryQuery */
        SkillHistoryQuery: {
            /** Name */
            name: string;
        };
        /** SkillInstallDepsCommand */
        SkillInstallDepsCommand: {
            /**
             * Binname
             * @default null
             */
            binName: string | null;
            /** Name */
            name: string;
        };
        /** SkillJudgeQuery */
        SkillJudgeQuery: {
            /** Name */
            name: string;
        };
        /** SkillModeCommand */
        SkillModeCommand: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** SkillRejectCommand */
        SkillRejectCommand: {
            /** Name */
            name: string;
        };
        /** SkillRemoveCommand */
        SkillRemoveCommand: {
            /** Name */
            name: string;
        };
        /** SkillSaveCommand */
        SkillSaveCommand: {
            /** Content */
            content: string;
            /** Name */
            name: string;
        };
        /** SkillSearchQuery */
        SkillSearchQuery: {
            /**
             * Limit
             * @default 0
             */
            limit: number;
            /** Q */
            q: string;
        };
        /** SkillsImportCommand */
        SkillsImportCommand: {
            /** Source */
            source: string;
        };
        /**
         * SkillsListQuery
         * @description No inputs.
         */
        SkillsListQuery: Record<string, never>;
        /**
         * SkillsQuarantineQuery
         * @description No inputs.
         */
        SkillsQuarantineQuery: Record<string, never>;
        /** SkillsResolveQuery */
        SkillsResolveQuery: {
            /** Source */
            source: string;
        };
        /**
         * SkillsResult
         * @description Carries a store status code + raw payload dict (escape hatch).
         */
        SkillsResult: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Status */
            status: number;
        };
        /** TokenMetadata */
        TokenMetadata: {
            /** Createdat */
            createdAt: number | null;
            /** Expiresat */
            expiresAt: number | null;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Lastusedat */
            lastUsedAt: number | null;
            /** Scopes */
            scopes: string[];
            /** Tokenid */
            tokenId: string;
        };
        /** WebuiThreadQuery */
        WebuiThreadQuery: {
            /** Key */
            key: string;
        };
        /** WebuiThreadResult */
        WebuiThreadResult: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_list_tokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListTokensQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTokensResult"];
                };
            };
        };
    };
    auth_issue_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueTokenCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueTokenResult"];
                };
            };
        };
    };
    auth_revoke_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeTokenCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeTokenResult"];
                };
            };
        };
    };
    config_channels_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelsListQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelsListResult"];
                };
            };
        };
    };
    commands_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandsListQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandsResult"];
                };
            };
        };
    };
    config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigGetQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigGetResult"];
                };
            };
        };
    };
    config_set: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSetCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSetResult"];
                };
            };
        };
    };
    cron_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CronListQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronListResult"];
                };
            };
        };
    };
    cron_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CronRemoveCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronRemoveResult"];
                };
            };
        };
    };
    cron_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CronRunCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronRunResult"];
                };
            };
        };
    };
    cron_toggle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CronToggleCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronToggleResult"];
                };
            };
        };
    };
    health_extras_ensure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtrasEnsureCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtrasEnsureResult"];
                };
            };
        };
    };
    health_extras_restart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtrasRestartCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtrasRestartResult"];
                };
            };
        };
    };
    health_extras_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtrasStatusQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtrasStatusResult"];
                };
            };
        };
    };
    health_logs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogsListQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsListResult"];
                };
            };
        };
    };
    memory_backlinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryBacklinksQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResult"];
                };
            };
        };
    };
    config_cross_encoder_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrossEncoderTestQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossEncoderTestResult"];
                };
            };
        };
    };
    memory_edge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryEdgeQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResult"];
                };
            };
        };
    };
    memory_entity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryEntityQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResult"];
                };
            };
        };
    };
    memory_entry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryEntryQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResult"];
                };
            };
        };
    };
    memory_forget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryForgetCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgetResult"];
                };
            };
        };
    };
    memory_graph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryGraphQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResult"];
                };
            };
        };
    };
    memory_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemorySearchQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResult"];
                };
            };
        };
    };
    memory_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemorySessionQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResult"];
                };
            };
        };
    };
    memory_subgraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemorySubgraphQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResult"];
                };
            };
        };
    };
    config_model_capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCapabilitiesQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCapabilitiesResult"];
                };
            };
        };
    };
    config_model_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelTestQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelTestResult"];
                };
            };
        };
    };
    config_models_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelsListQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsListResult"];
                };
            };
        };
    };
    oauth_disconnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthDisconnectCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStatusResult"];
                };
            };
        };
    };
    oauth_poll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthPollQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthPollResult"];
                };
            };
        };
    };
    oauth_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStartCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStartResult"];
                };
            };
        };
    };
    oauth_start_loopback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStartLoopbackCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStartLoopbackResult"];
                };
            };
        };
    };
    oauth_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthStatusQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthStatusResult"];
                };
            };
        };
    };
    secrets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretsListQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretsListResult"];
                };
            };
        };
    };
    secrets_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretDeleteCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretDeleteResult"];
                };
            };
        };
    };
    sessions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionsListQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsListResult"];
                };
            };
        };
    };
    sessions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionDeleteCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDeleteResult"];
                };
            };
        };
    };
    sessions_messages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionMessagesQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMessagesResult"];
                };
            };
        };
    };
    sessions_rename: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRenameCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRenameResult"];
                };
            };
        };
    };
    sessions_webui_thread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebuiThreadQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebuiThreadResult"];
                };
            };
        };
    };
    settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResult"];
                };
            };
        };
    };
    settings_provider_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsProviderUpdateCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResult"];
                };
            };
        };
    };
    settings_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResult"];
                };
            };
        };
    };
    settings_web_search_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsWebSearchUpdateCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResult"];
                };
            };
        };
    };
    skills_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillsListQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_describe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillDescribeQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_github_token_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GithubTokenTestQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_import_skill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillsImportCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_quarantine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillsQuarantineQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillsResolveQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillSearchQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillGetQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_approve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillApproveCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_file_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillFileQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_file_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillFileSaveCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_files: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillFilesQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillHistoryQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_install_deps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillInstallDepsCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_judge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillJudgeQuery"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_mode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillModeCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_reject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillRejectCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillRemoveCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
    skills_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillSaveCommand"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsResult"];
                };
            };
        };
    };
}
