export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** Assistant turn: accumulated model reasoning / thinking text. Built up
   * incrementally from ``reasoning_delta`` frames; finalized when
   * ``reasoning_end`` arrives. */
  reasoning?: string;
  /** True while ``reasoning_delta`` frames are still arriving for this turn.
   * Drives the shimmer header on ``ReasoningBubble``. */
  reasoningStreaming?: boolean;
  /** End-to-end wall time for this assistant turn (persisted ``latency_ms`` / ``turn_end``). */
  latencyMs?: number;
  /** For trace rows: structured tool-call events merged by ``call_id``.
   * Carries name / arguments / result / error so the UI can render
   * rich blocks (code diffs, exec IN/OUT) instead of flat text traces.
   * Mirrors the terminal TUI's ToolCallBubble. */
  toolEvents?: ToolProgressEvent[];
  /** When 'text', the content is pre-formatted plain text (output of a
   * slash command like /status or /memory show) and should be rendered
   * verbatim with whitespace preserved — NOT through the Markdown
   * pipeline (which collapses single newlines and treats tables as text).
   * Default 'markdown' replicates the legacy behaviour. */
  renderAs?: "text" | "markdown";
}


/** WebSocket snapshot for sustained goals (`goal_state` events; keyed by ``chat_id``). */
export interface GoalStateWsPayload {
  active: boolean;
  ui_summary?: string;
  objective?: string;
  /** Agent mode when not default (e.g. "plan"). */
  mode?: string;
  /** Set while an ask_user_question awaits the user's reply. */
  pending_question?: { question: string; options: string[] };
}

export interface ToolProgressEvent {
  version?: number;
  phase?: "start" | "end" | "error" | string;
  call_id?: string;
  name?: string;
  arguments?: unknown;
  result?: unknown;
  error?: unknown;
  files?: unknown[];
  embeds?: unknown[];
  progress?: { iteration?: number; tool?: string | null };
  nodes?: Array<{
    id: string;
    label?: string;
    status: "running" | "done" | "failed";
    route_label?: string | null;
    branches?: Array<{ id: string; label?: string; status: "running" | "done" | "failed" }>;
  }>;
}

// ---------------------------------------------------------------------------
// Work-panel types (useWorkState hook)
// ---------------------------------------------------------------------------

export interface WorkBranch {
  id: string;
  label?: string;
  status: "running" | "done" | "failed";
}

export interface WorkNode {
  id: string;
  label?: string;
  status: "running" | "done" | "failed" | "pending";
  branches?: WorkBranch[];
}

export interface WorkItem {
  kind: "workflow" | "subagent";
  id: string;
  label: string;
  status: "running" | "needs_input" | "done" | "failed";
  /** Workflow node tree; live frames override polled history. */
  nodes?: WorkNode[];
  /** Sub-agent live step count from progress.iteration. */
  steps?: number;
  /** The task (user input) given to this workflow run; absent for sub-agents and older runs. */
  task?: string;
  startedAt: number;
  endedAt: number | null;
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  title?: string;
  preview: string;
}

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
  /** Active preset name (carries the effort suffix, e.g. "default:high") so the
   *  composer's reasoning-effort picker is correct on first load. */
  model_preset?: string | null;
  /** True when this deploy gates bootstrap on a setup secret. When
   *  false, the gateway auto-mints tokens for localhost — there's
   *  nothing for the user to "log out from", so the webui hides the
   *  Logout button entirely (clicking it would otherwise strand the
   *  user on an auth form they can't fill). */
  requires_secret?: boolean;
}

export interface SettingsPayload {
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
  };
  providers: Array<{
    name: string;
    label: string;
    configured: boolean;
    oauth?: boolean;
    api_key_hint?: string | null;
    api_base?: string | null;
    default_api_base?: string | null;
  }>;
  web_search: {
    provider: string;
    api_key_hint?: string | null;
    base_url?: string | null;
    providers: Array<{
      name: string;
      label: string;
      credential: "none" | "api_key" | "base_url";
    }>;
  };
  runtime: {
    config_path: string;
  };
  requires_restart: boolean;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
}

export interface ProviderSettingsUpdate {
  provider: string;
  apiKey?: string;
  apiBase?: string;
}

export interface WebSearchSettingsUpdate {
  provider: string;
  apiKey?: string;
  baseUrl?: string;
}

export interface SecretEntry {
  name: string;
  service: string;
  account: string;
  description: string;
  scope: string[];
  origin: string;
  created_at: string;
  value_hint: string | null;
}

/** Full effective config (secret-masked) + its JSON schema, for the
 *  schema-driven settings form. */
export interface ConfigSnapshot {
  config: Record<string, unknown>;
  schema: Record<string, unknown>;
}

export interface SlashCommand {
  command: string;
  title: string;
  description: string;
  icon: string;
  argHint?: string;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

/** Provider-retry banner payload. ``final=true`` means retries are
 * exhausted — the next assistant message will be the error response.
 * ``delay_s=0`` on a non-final event means the heartbeat is firing
 * at chunk boundary (no actual wait left). */
export interface ApiRetryStatus {
  kind: "retry_wait" | "giving_up" | "exhausted_persistent";
  attempt: number;
  max_attempts: number | null;
  delay_s: number;
  persistent: boolean;
  final: boolean;
}

export type InboundEvent =
  | { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string }
  | {
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      tool_events?: ToolProgressEvent[];
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress" | "reasoning";
      /** Server-measured turn wall time when this frame finishes an assistant reply. */
      latency_ms?: number;
      /** Optional structured payload on progress frames (channel-specific).
       * Ignored by the webui — kept in the wire type for forward compat. */
      agent_ui?: { kind: string; data?: unknown };
      /** When 'text', the agent emitted pre-formatted plain text (slash
       * command output). The client should render verbatim with
       * whitespace preserved instead of feeding the body to Markdown.
       * Set by command handlers via OutboundMessage.metadata.render_as. */
      render_as?: "text" | "markdown";
    }
  | {
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
    }
  | {
      event: "reasoning_delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    }
  | {
      event: "reasoning_end";
      chat_id: string;
      stream_id?: string;
    }
  | {
      event: "runtime_model_updated";
      model_name: string;
      model_preset?: string | null;
    }
  | {
      event: "turn_end";
      chat_id: string;
      latency_ms?: number;
      /** Authoritative sustained-goal snapshot for this chat (same shape as ``goal_state`` events). */
      goal_state?: GoalStateWsPayload;
    }
  | {
      event: "goal_status";
      chat_id: string;
      /** Turn executing (user message through agent loop). */
      status: "running" | "idle";
      /** Server ``time.time()`` when ``status`` is ``running``. */
      started_at?: number;
    }
  | {
      event: "goal_state";
      chat_id: string;
      goal_state: GoalStateWsPayload;
    }
  | {
      /** Transient banner for provider retries / give-up. Never enters
       * the transcript. Carries the structured ``status`` payload the
       * provider's retry path emits (kind, attempt, max_attempts,
       * delay_s, persistent, final). */
      event: "api_status";
      chat_id: string;
      status: ApiRetryStatus;
      message?: string;
    }
  | { event: "session_updated"; chat_id: string }
  | {
      /** Live progress of a (manually triggered) memory-dream run, broadcast
       * to every connection. ``run_started`` / ``run_finished`` drive the Dream
       * view's "running" indicator; ``activity`` carries one digest item
       * (``item``) to prepend to the live feed as the dream produces it. */
      event: "dream_progress";
      kind: "run_started" | "activity" | "run_finished";
      item?: {
        kind: string;
        summary: string;
        ref: string | null;
        ref_kind: string | null;
        at_ms: number;
      };
      /** On ``run_finished``: false when the consolidation passes errored. */
      ok?: boolean;
    }
  | {
      /** Ack for a `secret_store` frame — the credential was written to
       * the local secret store (or rejected). Carries no secret value. */
      event: "secret_stored";
      request_id: string;
      ok: boolean;
      name?: string;
      detail?: string;
    }
  | {
      /** Reply to an ``audio_transcribe`` frame (spec §5.4). Carries the
       * transcript text, or an error reason when transcription failed.
       * Intermediate events with ``status`` set signal progress phases
       * (model download, load, transcribing) and keep the WS alive.
       * Only the terminal event (no ``status``) carries ``transcript``. */
      event: "audio_transcript";
      request_id: string;
      chat_id?: string;
      name?: string;
      transcript?: string;
      error?: string;
      status?: "downloading" | "loading" | "transcribing";
      /** Bytes received so far during a ``downloading`` phase. */
      bytes?: number;
      /** Total expected bytes during a ``downloading`` phase (absent when
       * Content-Length is unknown). */
      total?: number;
    }
  | { event: "voice_state"; chat_id: string; state: string }
  | { event: "voice_audio"; chat_id: string; url: string; mime: string }
  | { event: "voice_preview_audio"; url?: string; mime?: string; error?: string }
  | { event: "error"; chat_id?: string; detail?: string };

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

/** Response shape for ``GET .../webui-thread`` (server-built transcript replay). */
export interface WebuiThreadPersistedPayload {
  schemaVersion: number;
  sessionKey?: string;
  savedAt?: string;
  messages: UIMessage[];
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      /** Marks messages sent by the embedded WebUI, without changing the
       * generic websocket protocol for other clients. */
      webui?: true;
    }
  | {
      /** Store a credential straight into durin's secret store. The
       * value rides the (already-authenticated) socket as a JSON field —
       * never a URL query — and never enters the agent conversation. */
      type: "secret_store";
      request_id: string;
      name: string;
      service: string;
      value: string;
      scope?: string[];
      account?: string;
      description?: string;
      /** When set, the agent on this chat is told (metadata only, no
       * value) that the secret is now available. */
      chat_id?: string;
    }
  | {
      /** Start a streaming on-demand audit of a quarantined skill. Reasoning
       arrives as ``reasoning_delta`` on ``audit:<name>``; the terminal
       ``skill_audit_done`` carries the structured result. */
      type: "skill_judge";
      chat_id: string;
      name: string;
    }
  | {
      /** Ask the server to transcribe one audio attachment (spec §5.4). The
       * server stores the audio, transcribes it, and replies with an
       * ``audio_transcript`` event keyed by ``request_id``. */
      type: "audio_transcribe";
      request_id: string;
      chat_id: string;
      media: OutboundMedia[];
    }
  | { type: "voice_start"; chat_id: string; webui: true }
  | { type: "voice_stop"; chat_id: string; webui: true }
  | { type: "voice_utterance"; chat_id: string; media: OutboundMedia[]; webui: true }
  | { type: "voice_barge_in"; chat_id: string; webui: true }
  | { type: "voice_read_all"; chat_id: string; text: string; webui: true }
  | { type: "voice_preview"; voice: string | null; language: string | null; webui: true };

// ---------------------------------------------------------------------------
// MCP server management (snake_case to match the /api/v1 wire shape —
// service Results are dumped with model_dump(), i.e. by field name).
// ---------------------------------------------------------------------------

export interface McpToolInfo {
  name: string;
  description: string;
}

/** One of: connected | connecting | failed | needs_auth | disabled. */
export type McpStatus =
  | "connected"
  | "connecting"
  | "failed"
  | "needs_auth"
  | "disabled";

export interface McpServerSummary {
  name: string;
  transport: string;
  target: string;
  enabled: boolean;
  oauth_required: boolean;
  oauth_authenticated: boolean;
  status: McpStatus;
  tool_count: number;
  error: string | null;
}

export interface McpSamplingConfig {
  enabled?: boolean;
  model?: string | null;
  allowed_models?: string[];
  max_tokens_cap?: number;
  requests_per_minute?: number;
  allow_tools?: boolean;
  max_tool_rounds?: number;
}

export interface McpOauthStaticConfig {
  scope?: string | null;
  client_id?: string | null;
  client_secret?: string | null;
  callback_port?: number;
}

export interface McpServerConfig {
  enabled?: boolean;
  type?: "stdio" | "sse" | "streamableHttp" | null;
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  url?: string;
  headers?: Record<string, string>;
  tool_timeout?: number;
  tool_timeouts?: Record<string, number>;
  catalog_timeout?: number;
  keepalive_interval?: number;
  enabled_tools?: string[];
  oauth?: boolean | McpOauthStaticConfig | null;
  allow_private_url?: boolean;
  spawn_egress_policy?: "warn" | "refuse" | "off";
  malware_check?: boolean;
  sampling?: McpSamplingConfig;
}

export interface McpServerDetail {
  name: string;
  transport: string;
  target: string;
  enabled: boolean;
  oauth_required: boolean;
  oauth_authenticated: boolean;
  status: McpStatus;
  error: string | null;
  tools: McpToolInfo[];
  config: McpServerConfig;
}

export interface McpOauthLoginResult {
  authorization_url: string;
  state: string;
}

export interface McpRegistryHit {
  name: string;
  ref: string;
  registry: string;
  kind: string; // remote | local | both
  description: string;
  signals: Record<string, unknown>;
}

export interface McpRegistryEnvVar {
  name: string;
  description: string;
  is_required: boolean;
  is_secret: boolean;
  default: string | null;
  help_url?: string | null;
}

export interface McpRegistryPackage {
  registry_type: string;
  identifier: string;
  version: string;
  runtime_hint: string;
  transport_type: string;
  runtime_arguments: string[];
  package_arguments: string[];
  env: McpRegistryEnvVar[];
}

export interface McpRegistryRemote {
  transport_type: string;
  url: string;
  headers: McpRegistryEnvVar[];
}

export interface McpRegistryServerDetail {
  name: string;
  ref: string;
  description: string;
  version: string;
  repository: string;
  packages: McpRegistryPackage[];
  remotes: McpRegistryRemote[];
}

export interface McpRuntimeStatus {
  kind: string; // "local" | "remote"
  runtime: string; // "docker" | "npx" | "uvx" | ""
  present: boolean;
  auto_installable: boolean;
  install_command: string;
}

export interface McpOauthCapability {
  oauth_capable: boolean;
}

export interface McpUpdateInfo {
  name: string;
  current: string;
  latest: string;
}
