#!/usr/bin/env python
"""Generate the webui colour tokens from durin/cli/theme.py.

Emits the `@layer base { ... }` token block for webui/src/globals.css:
durin's palettes mapped onto shadcn/ui's token names, in HSL-triple form
(what Tailwind's `hsl(var(--x))` expects). Run after editing the palettes
and paste the output over the token block in globals.css.

    python scripts/gen_webui_tokens.py

durin's accent is the brand colour; it maps to `--primary` (the CTA fill)
and `--ring` (focus). Outline/ghost buttons stay neutral, so the accent
lands on genuine primary actions without flooding the UI.
"""

from __future__ import annotations

import colorsys
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from durin.cli.theme import PALETTES  # noqa: E402


def hsl(hex_color: str) -> str:
    """`#rrggbb` -> shadcn HSL triple, e.g. `204 60% 53%`."""
    raw = hex_color.lstrip("#")
    r, g, b = (int(raw[i : i + 2], 16) / 255 for i in (0, 2, 4))
    hue, light, sat = colorsys.rgb_to_hls(r, g, b)
    return f"{round(hue * 360)} {round(sat * 100)}% {round(light * 100)}%"


# shadcn token  ->  durin.cli.theme.Palette field
MAP: list[tuple[str, str]] = [
    ("background", "bg"),
    ("foreground", "text"),
    ("card", "surface"),
    ("card-foreground", "text"),
    ("popover", "surface"),
    ("popover-foreground", "text"),
    ("primary", "accent"),
    ("primary-foreground", "accent_text"),
    ("secondary", "surface_2"),
    ("secondary-foreground", "text"),
    ("muted", "surface_2"),
    ("muted-foreground", "muted"),
    ("accent", "surface_2"),
    ("accent-foreground", "text"),
    ("destructive", "danger"),
    ("destructive-foreground", "bg"),
    ("border", "border"),
    ("input", "border"),
    ("ring", "accent"),
    ("sidebar", "bg"),
    ("sidebar-foreground", "text"),
    ("sidebar-accent", "surface_2"),
    ("sidebar-accent-foreground", "text"),
    ("sidebar-border", "border"),
]

SELECTORS: list[tuple[str, str, str]] = [
    ("ithildin", "light", ":root"),
    ("ithildin", "dark", ".dark"),
    ("forge", "light", '[data-palette="forge"]'),
    ("forge", "dark", '[data-palette="forge"].dark'),
    ("mithril", "light", '[data-palette="mithril"]'),
    ("mithril", "dark", '[data-palette="mithril"].dark'),
]


def block(palette: str, mode: str, selector: str) -> str:
    entry = PALETTES[palette][mode]
    lines = [f"  {selector} {{"]
    for var, field in MAP:
        lines.append(f"    --{var}: {hsl(getattr(entry, field))};")
    if selector == ":root":
        lines.append("    --radius: 0.4375rem;")
    lines.append("  }")
    return "\n".join(lines)


def main() -> None:
    parts = [
        "/* durin design tokens — GENERATED by scripts/gen_webui_tokens.py",
        "   from durin/cli/theme.py (the mirror of design/tokens.css).",
        "   Two axes: palette (data-palette) x mode (.dark). Do not edit by hand. */",
        "@layer base {",
        "\n\n".join(block(*sel) for sel in SELECTORS),
        "}",
    ]
    print("\n".join(parts))


if __name__ == "__main__":
    main()
